import { memo, useCallback, useEffect, useMemo, useRef, useState, type CSSProperties } from 'react';
import { ChevronLeft, RotateCcw } from 'lucide-react';
import { lavaValleyAssets } from '../../assets/adventure/lava-valley';
import type { OwnedDinosaur } from '../../types/game';
import { createLavaValleyShopDropPlan, LAVA_VALLEY_COIN_PATTERNS, LAVA_VALLEY_COLLECTIBLE_LANES, LAVA_VALLEY_RARE_FRAGMENT_SPAWN_CHANCE, LAVA_VALLEY_REWARDS_CONFIG, MAX_RARE_FRAGMENTS_PER_RUN, normalizeLavaValleyRewards, shouldCommitLavaValleyRewards, type LavaValleyEndReason, type MinigameItemReward, type MinigameRunRewards } from '../../config/minigameConfig';
import { getItemConfig } from '../../config/itemConfig';
import { shopItemImages } from '../../assets/shop';
import { preloadImages } from '../../utils/preloadImages';

export const LAVA_RUNNER_CONFIG = { gameDuration: LAVA_VALLEY_REWARDS_CONFIG.gameDurationSeconds, introMs: 1800, collectibleIntervalMin: 2600, collectibleIntervalMax: 3900, invincibleMs: 1400, playerX: 27, trackBottom: 12, footEffectBottom: 20, maxObstacles: 2, checkpointProgress: .5, dashDurationMs: 1000, dashRecoveryMs: 200, dashCooldownMs: 2000, dashSpeedMultiplier: 1.9 } as const;
export const LAVA_VALLEY_DIFFICULTY = {
  easy: { playerVisualScale: 1.28, obstacleVisualScale: 1.2, runSpeed: 26.5, obstacleSpawnIntervalMin: 3100, obstacleSpawnIntervalMax: 4400, jumpVelocity: 101, gravity: 195, apexHoldMs: 120, playerHitboxScale: .68, obstacleHitboxScale: .72, coyoteTimeMs: 180, jumpBufferMs: 250, jumpGuideEnabled: true, geyserChance: .18 },
  normal: { playerVisualScale: 1.25, obstacleVisualScale: 1.18, runSpeed: 32, obstacleSpawnIntervalMin: 2400, obstacleSpawnIntervalMax: 3600, jumpVelocity: 98, gravity: 215, apexHoldMs: 100, playerHitboxScale: .76, obstacleHitboxScale: .78, coyoteTimeMs: 110, jumpBufferMs: 120, jumpGuideEnabled: false, geyserChance: .35 },
  challenge: { playerVisualScale: 1.25, obstacleVisualScale: 1.18, runSpeed: 36, obstacleSpawnIntervalMin: 2100, obstacleSpawnIntervalMax: 3100, jumpVelocity: 96, gravity: 228, apexHoldMs: 80, playerHitboxScale: .84, obstacleHitboxScale: .88, coyoteTimeMs: 70, jumpBufferMs: 70, jumpGuideEnabled: false, geyserChance: .5 },
} as const;

type ObstacleKind = 'rock' | 'geyser';
type CollectibleKind = 'coin' | 'shard' | 'shopItem';
type RunnerItemKind = ObstacleKind | CollectibleKind | 'checkpoint';
type RunnerItem = { id: number; kind: RunnerItemKind; x: number; height: number; itemId?: string; label?: string };
type Result = 'playing' | 'success' | 'failure';
type Difficulty = keyof typeof LAVA_VALLEY_DIFFICULTY;
type PickupFeedback = { id: number; kind: CollectibleKind | 'checkpoint'; label: string };
type Burst = { id: number; kind: 'jump' | 'landing' | 'coin' | 'item' | 'hurt' | 'checkpoint' | 'clear'; x: number; y: number };

const OBSTACLE_CLEARANCE: Record<ObstacleKind, number> = { rock: 6.5, geyser: 9 };
const OBSTACLE_WIDTH: Record<ObstacleKind, number> = { rock: 7, geyser: 6 };
const randomBetween = (min: number, max: number) => min + Math.random() * (max - min);
const isObstacle = (kind: RunnerItemKind): kind is ObstacleKind => kind === 'rock' || kind === 'geyser';
const isCollectible = (kind: RunnerItemKind): kind is CollectibleKind => kind === 'coin' || kind === 'shard' || kind === 'shopItem';

export interface LavaPathPrototypeProps { dinosaur: OwnedDinosaur; onExit: () => void; runId: string; onFinishRun: (runId: string, rewards: MinigameRunRewards) => MinigameRunRewards; onRetry: () => void; externalMainModalOpen?: boolean }

const PLAYER_PRELOAD_ASSETS = [lavaValleyAssets.player.idle, lavaValleyAssets.player.runSheet, lavaValleyAssets.player.jumpUp, lavaValleyAssets.player.fall, lavaValleyAssets.player.hurt, lavaValleyAssets.player.victory] as const;

type LavaValleyPlayerProps = { intro: boolean; invincible: boolean; jumping: boolean; jumpY: number; rising: boolean; success: boolean };

const LavaValleyPlayer = memo(function LavaValleyPlayer({ intro, invincible, jumping, jumpY, rising, success }: LavaValleyPlayerProps) {
  const stillImage = success ? lavaValleyAssets.player.victory : invincible ? lavaValleyAssets.player.hurt : jumping ? (rising ? lavaValleyAssets.player.jumpUp : lavaValleyAssets.player.fall) : intro ? lavaValleyAssets.player.idle : null;
  return <div className={`lava-runner__dino ${jumping ? 'lava-runner__dino--jump' : ''} ${invincible ? 'lava-runner__dino--hit' : ''}`} style={{ '--lava-jump-y': `${jumpY}%` } as CSSProperties}>
    {stillImage ? <img src={stillImage} alt="용암계곡 카르노타우루스" draggable={false} /> : <span className="lava-runner__run-sprite" role="img" aria-label="달리는 카르노타우루스" />}
  </div>;
});

export function LavaPathPrototype({ onExit, runId, onFinishRun, onRetry, externalMainModalOpen = false }: LavaPathPrototypeProps) {
  const [items, setItems] = useState<RunnerItem[]>([]);
  const [coins, setCoins] = useState(0), [shopItemCount, setShopItemCount] = useState(0), [rareShards, setRareShards] = useState(0), [health, setHealth] = useState(3), [timeLeft, setTimeLeft] = useState(LAVA_RUNNER_CONFIG.gameDuration);
  const [jumping, setJumping] = useState(false), [jumpY, setJumpY] = useState(0), [invincible, setInvincible] = useState(false), [paused, setPaused] = useState(false), [result, setResult] = useState<Result>('playing');
  const [intro, setIntro] = useState(true), [showResult, setShowResult] = useState(false), [finishStep, setFinishStep] = useState<0 | 1 | 2>(0);
  const [committedRewards, setCommittedRewards] = useState<MinigameRunRewards | null>(null);
  const [difficulty, setDifficulty] = useState<Difficulty>('easy'), [checkpointStage, setCheckpointStage] = useState<1 | 2>(1), [pickupFeedback, setPickupFeedback] = useState<PickupFeedback | null>(null);
  const [jumpGuideActive, setJumpGuideActive] = useState(false), [jumpPressed, setJumpPressed] = useState(false), [burst, setBurst] = useState<Burst | null>(null), [speech, setSpeech] = useState<string | null>(null), [combo, setCombo] = useState(false);
  const [assetsReady, setAssetsReady] = useState(false);
  const [dashing, setDashing] = useState(false), [dashCooldownMs, setDashCooldownMs] = useState(0);
  const [attempt, setAttempt] = useState(0);
  const itemsRef = useRef<RunnerItem[]>([]), healthRef = useRef(3), resultRef = useRef<Result>('playing'), jumpingRef = useRef(false), invincibleUntilRef = useRef(0), pausedRef = useRef(false), introRef = useRef(true);
  const startTimeRef = useRef(0), lastFrameRef = useRef(0), nextObstacleRef = useRef(0), nextCollectibleRef = useRef(0), nextIdRef = useRef(1), pauseStartedRef = useRef(0), checkpointSpawnedRef = useRef(false), checkpointPassedRef = useRef(false);
  const dashUntilRef = useRef(0), dashReadyAtRef = useRef(0);
  const jumpYRef = useRef(0), jumpVelocityRef = useRef(0), apexHoldUntilRef = useRef(0), difficultyRef = useRef<Difficulty>('easy'), lastGroundedAtRef = useRef(performance.now()), jumpBufferedUntilRef = useRef(0), hasJumpedSinceGroundRef = useRef(false);
  const guidedObstacleIdsRef = useRef(new Set<number>()), highGuideCountRef = useRef(0), jumpGuideTimerRef = useRef<number | null>(null), coinStreakRef = useRef({ count: 0, lastAt: 0, lastComboAt: 0 });
  const coinsRef = useRef(0), shopItemsRef = useRef<MinigameItemReward[]>([]), rareShardsRef = useRef(0), rewardCommittedRef = useRef(false);
  const shopDropPlanRef = useRef(createLavaValleyShopDropPlan()), spawnedShopDropIdsRef = useRef(new Set<number>()), timersRef = useRef<number[]>([]);

  const later = useCallback((action: () => void, delay: number) => { const timer = window.setTimeout(action, delay); timersRef.current.push(timer); return timer; }, []);
  const showBurst = useCallback((kind: Burst['kind'], x: number, y: number) => setBurst({ id: nextIdRef.current++, kind, x, y }), []);
  const showFeedback = useCallback((kind: PickupFeedback['kind'], label: string) => { const feedback = { id: nextIdRef.current++, kind, label }; setPickupFeedback(feedback); later(() => setPickupFeedback((current) => current?.id === feedback.id ? null : current), 850); }, [later]);
  const showSpeech = useCallback((message: string) => { setSpeech(message); later(() => setSpeech((current) => current === message ? null : current), 2100); }, [later]);
  const restartCurrentSession = useCallback((_reason: Extract<LavaValleyEndReason, 'hp_depleted' | 'manual_restart'>) => {
    timersRef.current.forEach(window.clearTimeout); timersRef.current = [];
    itemsRef.current = []; healthRef.current = 3; resultRef.current = 'playing'; jumpingRef.current = false; invincibleUntilRef.current = 0; pausedRef.current = false; introRef.current = true;
    startTimeRef.current = 0; lastFrameRef.current = 0; nextObstacleRef.current = 0; nextCollectibleRef.current = 0; pauseStartedRef.current = 0; checkpointSpawnedRef.current = false; checkpointPassedRef.current = false; dashUntilRef.current = 0; dashReadyAtRef.current = 0;
    jumpYRef.current = 0; jumpVelocityRef.current = 0; apexHoldUntilRef.current = 0; lastGroundedAtRef.current = performance.now(); jumpBufferedUntilRef.current = 0; hasJumpedSinceGroundRef.current = false; guidedObstacleIdsRef.current.clear(); highGuideCountRef.current = 0;
    coinsRef.current = 0; rareShardsRef.current = 0; shopItemsRef.current = []; rewardCommittedRef.current = false; shopDropPlanRef.current = createLavaValleyShopDropPlan(); spawnedShopDropIdsRef.current.clear(); coinStreakRef.current = { count: 0, lastAt: 0, lastComboAt: 0 };
    setItems([]); setCoins(0); setRareShards(0); setShopItemCount(0); setHealth(3); setTimeLeft(LAVA_RUNNER_CONFIG.gameDuration); setJumping(false); setJumpY(0); setInvincible(false); setPaused(false); setResult('playing'); setShowResult(false); setFinishStep(0); setCommittedRewards(null); setCheckpointStage(1); setPickupFeedback(null); setJumpGuideActive(false); setJumpPressed(false); setBurst(null); setSpeech(null); setCombo(false); setDashing(false); setDashCooldownMs(0); setIntro(true); setAttempt((value) => value + 1);
  }, []);

  const startJump = useCallback(() => { const preset = LAVA_VALLEY_DIFFICULTY[difficultyRef.current]; jumpingRef.current = true; hasJumpedSinceGroundRef.current = true; jumpBufferedUntilRef.current = 0; apexHoldUntilRef.current = 0; jumpVelocityRef.current = preset.jumpVelocity; setJumping(true); showBurst('jump', LAVA_RUNNER_CONFIG.playerX - 1, LAVA_RUNNER_CONFIG.footEffectBottom); }, [showBurst]);
  const jump = useCallback(() => { if (resultRef.current !== 'playing' || pausedRef.current || introRef.current) return; const now = performance.now(), preset = LAVA_VALLEY_DIFFICULTY[difficultyRef.current]; const canUseCoyoteTime = !hasJumpedSinceGroundRef.current && now - lastGroundedAtRef.current <= preset.coyoteTimeMs; if (!jumpingRef.current || canUseCoyoteTime) { startJump(); return; } jumpBufferedUntilRef.current = now + preset.jumpBufferMs; }, [startJump]);
  const dash = useCallback(() => { const now = performance.now(); if (resultRef.current !== 'playing' || pausedRef.current || introRef.current || now < dashReadyAtRef.current) return; dashUntilRef.current = now + LAVA_RUNNER_CONFIG.dashDurationMs; dashReadyAtRef.current = now + LAVA_RUNNER_CONFIG.dashCooldownMs; setDashing(true); setDashCooldownMs(LAVA_RUNNER_CONFIG.dashCooldownMs); showBurst('jump', LAVA_RUNNER_CONFIG.playerX - 5, LAVA_RUNNER_CONFIG.footEffectBottom); }, [showBurst]);
  const openSettings = () => { if (resultRef.current !== 'playing' || introRef.current) return; pauseStartedRef.current = performance.now(); pausedRef.current = true; setPaused(true); };
  const closeSettings = () => { const pausedFor = performance.now() - pauseStartedRef.current; startTimeRef.current += pausedFor; nextObstacleRef.current += pausedFor; nextCollectibleRef.current += pausedFor; invincibleUntilRef.current += pausedFor; if (dashUntilRef.current) dashUntilRef.current += pausedFor; if (dashReadyAtRef.current) dashReadyAtRef.current += pausedFor; if (apexHoldUntilRef.current) apexHoldUntilRef.current += pausedFor; lastFrameRef.current = performance.now(); pausedRef.current = false; setPaused(false); };
  const chooseDifficulty = (next: Difficulty) => { difficultyRef.current = next; setDifficulty(next); setJumpGuideActive(false); const preset = LAVA_VALLEY_DIFFICULTY[next]; nextObstacleRef.current = performance.now() + randomBetween(preset.obstacleSpawnIntervalMin, preset.obstacleSpawnIntervalMax); };
  const finish = useCallback((next: Exclude<Result, 'playing'>) => { if (resultRef.current !== 'playing') return; resultRef.current = next; itemsRef.current = []; setItems([]); const reason: LavaValleyEndReason = next === 'success' ? 'completed' : 'hp_depleted'; if (shouldCommitLavaValleyRewards(reason) && !rewardCommittedRef.current) { rewardCommittedRef.current = true; const rewards = normalizeLavaValleyRewards({ coins: coinsRef.current, rareFragments: rareShardsRef.current, shopItems: shopItemsRef.current }); setCommittedRewards(onFinishRun(runId, rewards)); } setResult(next); if (next === 'success') { setFinishStep(1); showBurst('clear', 70, 48); later(() => setFinishStep(2), 700); later(() => setShowResult(true), 1500); } else { setCommittedRewards(null); setShowResult(true); } }, [later, onFinishRun, runId, showBurst]);

  useEffect(() => {
    let cancelled = false;
    setAssetsReady(false);
    preloadImages(PLAYER_PRELOAD_ASSETS).then(() => { if (!cancelled) setAssetsReady(true); }).catch((error) => console.error(error));
    return () => { cancelled = true; };
  }, []);
  useEffect(() => { if (!assetsReady) return; const timer = later(() => { introRef.current = false; setIntro(false); const now = performance.now(); startTimeRef.current = now; lastFrameRef.current = now; nextObstacleRef.current = now + 1500; nextCollectibleRef.current = now + 1000; showSpeech('점프 버튼을 눌러 장애물을 피해요!'); }, LAVA_RUNNER_CONFIG.introMs); return () => window.clearTimeout(timer); }, [assetsReady, attempt, later, showSpeech]);
  useEffect(() => { const keyDown = (event: KeyboardEvent) => { if ((event.code === 'Space' || event.code === 'ArrowUp') && !event.repeat) { event.preventDefault(); jump(); } }; window.addEventListener('keydown', keyDown); return () => window.removeEventListener('keydown', keyDown); }, [jump]);
  useEffect(() => { const keyDown = (event: KeyboardEvent) => { if ((event.code === 'ShiftLeft' || event.code === 'ShiftRight') && !event.repeat) { event.preventDefault(); dash(); } }; window.addEventListener('keydown', keyDown); return () => window.removeEventListener('keydown', keyDown); }, [dash]);
  useEffect(() => () => { if (jumpGuideTimerRef.current) window.clearTimeout(jumpGuideTimerRef.current); timersRef.current.forEach(window.clearTimeout); }, []);
  useEffect(() => {
    let frame = 0;
    const spawnObstacle = (now: number, preset: typeof LAVA_VALLEY_DIFFICULTY[Difficulty]) => { const count = itemsRef.current.filter((item) => isObstacle(item.kind)).length, spawnAreaBusy = itemsRef.current.some((item) => !isObstacle(item.kind) && item.x > 78); if (count < LAVA_RUNNER_CONFIG.maxObstacles && !spawnAreaBusy) { const kind: ObstacleKind = Math.random() < preset.geyserChance ? 'geyser' : 'rock'; itemsRef.current.push({ id: nextIdRef.current++, kind, x: 110, height: 0 }); } nextObstacleRef.current = now + randomBetween(preset.obstacleSpawnIntervalMin, preset.obstacleSpawnIntervalMax); };
    const spawnCollectible = (now: number) => { const spawnAreaBusy = itemsRef.current.some((item) => isObstacle(item.kind) && item.x > 82), specialOnScreen = itemsRef.current.some((item) => item.kind === 'shard' || item.kind === 'shopItem'); if (!spawnAreaBusy) { const roll = Math.random(); if (rareShardsRef.current < MAX_RARE_FRAGMENTS_PER_RUN && !specialOnScreen && roll < LAVA_VALLEY_RARE_FRAGMENT_SPAWN_CHANCE) itemsRef.current.push({ id: nextIdRef.current++, kind: 'shard', x: 110, height: Math.random() < .55 ? LAVA_VALLEY_COLLECTIBLE_LANES.low : LAVA_VALLEY_COLLECTIBLE_LANES.high }); else { const pattern = LAVA_VALLEY_COIN_PATTERNS[Math.floor(Math.random() * LAVA_VALLEY_COIN_PATTERNS.length)]; pattern.forEach((height, index) => itemsRef.current.push({ id: nextIdRef.current++, kind: 'coin', x: 108 + index * 7, height })); } } nextCollectibleRef.current = now + randomBetween(LAVA_RUNNER_CONFIG.collectibleIntervalMin, LAVA_RUNNER_CONFIG.collectibleIntervalMax); };
    const spawnScheduledShopItem = (elapsedSeconds: number) => { const scheduled = shopDropPlanRef.current.find((drop) => !spawnedShopDropIdsRef.current.has(drop.id) && elapsedSeconds >= drop.spawnAtSeconds); if (!scheduled || itemsRef.current.some((item) => item.x > 78)) return; const item = getItemConfig(scheduled.itemId); if (!item) return; spawnedShopDropIdsRef.current.add(scheduled.id); const height = Math.random() < .7 ? LAVA_VALLEY_COLLECTIBLE_LANES.low : LAVA_VALLEY_COLLECTIBLE_LANES.high; itemsRef.current.push({ id: nextIdRef.current++, kind: 'shopItem', itemId: item.id, label: item.name, x: 110, height }); };
    const tick = (now: number) => {
      if (introRef.current || pausedRef.current) { lastFrameRef.current = now; frame = requestAnimationFrame(tick); return; }
      const preset = LAVA_VALLEY_DIFFICULTY[difficultyRef.current], elapsedMs = now - startTimeRef.current, remaining = Math.max(0, Math.ceil(LAVA_RUNNER_CONFIG.gameDuration - elapsedMs / 1000)); setTimeLeft((current) => current === remaining ? current : remaining);
      if (!remaining) { finish('success'); return; }
      const delta = Math.min((now - (lastFrameRef.current || now)) / 1000, .04); lastFrameRef.current = now; setInvincible(now < invincibleUntilRef.current);
      const isDashing = now < dashUntilRef.current; setDashing((current) => current === isDashing ? current : isDashing); const nextDashCooldown = Math.max(0, dashReadyAtRef.current - now); setDashCooldownMs((current) => Math.ceil(current / 100) === Math.ceil(nextDashCooldown / 100) ? current : nextDashCooldown);
      const recoveryRatio = Math.max(0, Math.min(1, (dashUntilRef.current + LAVA_RUNNER_CONFIG.dashRecoveryMs - now) / LAVA_RUNNER_CONFIG.dashRecoveryMs));
      const movementMultiplier = isDashing ? LAVA_RUNNER_CONFIG.dashSpeedMultiplier : 1 + (LAVA_RUNNER_CONFIG.dashSpeedMultiplier - 1) * recoveryRatio;
      if (jumpingRef.current) { if (now >= apexHoldUntilRef.current) { const previousVelocity = jumpVelocityRef.current; jumpVelocityRef.current -= preset.gravity * delta; if (previousVelocity > 0 && jumpVelocityRef.current <= 0) { jumpVelocityRef.current = -0.01; apexHoldUntilRef.current = now + preset.apexHoldMs; } else jumpYRef.current += jumpVelocityRef.current * delta; } if (jumpYRef.current <= 0) { jumpYRef.current = 0; jumpVelocityRef.current = 0; apexHoldUntilRef.current = 0; jumpingRef.current = false; hasJumpedSinceGroundRef.current = false; lastGroundedAtRef.current = now; setJumping(false); showBurst('landing', LAVA_RUNNER_CONFIG.playerX - 1, LAVA_RUNNER_CONFIG.footEffectBottom); if (now <= jumpBufferedUntilRef.current) startJump(); } setJumpY(jumpYRef.current); } else { lastGroundedAtRef.current = now; hasJumpedSinceGroundRef.current = false; }
      if (now >= nextObstacleRef.current) spawnObstacle(now, preset);
      if (now >= nextCollectibleRef.current) spawnCollectible(now);
      spawnScheduledShopItem(elapsedMs / 1000);
      if (!checkpointSpawnedRef.current && elapsedMs >= LAVA_RUNNER_CONFIG.gameDuration * 1000 * LAVA_RUNNER_CONFIG.checkpointProgress && !itemsRef.current.some((item) => isObstacle(item.kind) && item.x > 72)) { checkpointSpawnedRef.current = true; itemsRef.current.push({ id: nextIdRef.current++, kind: 'checkpoint', x: 112, height: 0 }); }
      itemsRef.current = itemsRef.current.map((item) => ({ ...item, x: item.x - preset.runSpeed * movementMultiplier * delta })).filter((item) => item.x > -15);
      if (preset.jumpGuideEnabled) { const guideTarget = itemsRef.current.find((item) => (isObstacle(item.kind) || (isCollectible(item.kind) && item.height === LAVA_VALLEY_COLLECTIBLE_LANES.high && highGuideCountRef.current < 2)) && item.x > LAVA_RUNNER_CONFIG.playerX && item.x <= LAVA_RUNNER_CONFIG.playerX + 34 && !guidedObstacleIdsRef.current.has(item.id)); if (guideTarget) { guidedObstacleIdsRef.current.add(guideTarget.id); if (isCollectible(guideTarget.kind)) highGuideCountRef.current += 1; setJumpGuideActive(false); requestAnimationFrame(() => setJumpGuideActive(true)); if (jumpGuideTimerRef.current) window.clearTimeout(jumpGuideTimerRef.current); jumpGuideTimerRef.current = window.setTimeout(() => setJumpGuideActive(false), 650); } }
      const removed = new Set<number>();
      for (const item of itemsRef.current) {
        if (item.kind === 'checkpoint') { if (!checkpointPassedRef.current && item.x <= LAVA_RUNNER_CONFIG.playerX) { checkpointPassedRef.current = true; setCheckpointStage(2); showFeedback('checkpoint', '체크포인트!'); showBurst('checkpoint', LAVA_RUNNER_CONFIG.playerX + 8, 20); } continue; }
        if (isCollectible(item.kind)) { if (Math.abs(item.x - LAVA_RUNNER_CONFIG.playerX) <= 7 && Math.abs(jumpYRef.current - item.height) <= 9) { removed.add(item.id); showBurst(item.kind === 'coin' ? 'coin' : 'item', item.x, item.height + 14); if (item.kind === 'coin') { coinsRef.current += 1; setCoins(coinsRef.current); showFeedback('coin', '+1'); const streak = coinStreakRef.current; streak.count = now - streak.lastAt <= 1800 ? streak.count + 1 : 1; streak.lastAt = now; if (streak.count >= 3 && now - streak.lastComboAt > 5000) { streak.lastComboAt = now; streak.count = 0; setCombo(true); later(() => setCombo(false), 900); } } if (item.kind === 'shopItem' && item.itemId) { const existing = shopItemsRef.current.find((reward) => reward.itemId === item.itemId); shopItemsRef.current = existing ? shopItemsRef.current.map((reward) => reward.itemId === item.itemId ? { ...reward, quantity: reward.quantity + 1 } : reward) : [...shopItemsRef.current, { itemId: item.itemId, quantity: 1 }]; setShopItemCount((value) => value + 1); showFeedback('shopItem', (item.label ?? '아이템') + ' 획득!'); } if (item.kind === 'shard' && rareShardsRef.current < MAX_RARE_FRAGMENTS_PER_RUN) { rareShardsRef.current += 1; setRareShards(rareShardsRef.current); showFeedback('shard', '희귀조각 획득!'); showSpeech('희귀조각이다!'); if (rareShardsRef.current >= MAX_RARE_FRAGMENTS_PER_RUN) itemsRef.current = itemsRef.current.filter((candidate) => candidate.kind !== 'shard' || candidate.id === item.id); } } continue; }
        const collisionDistance = (10 * preset.playerHitboxScale + OBSTACLE_WIDTH[item.kind] * preset.obstacleHitboxScale) / 2;
        if (Math.abs(item.x - LAVA_RUNNER_CONFIG.playerX) <= collisionDistance && jumpYRef.current < OBSTACLE_CLEARANCE[item.kind] && now >= invincibleUntilRef.current) { removed.add(item.id); healthRef.current -= 1; setHealth(healthRef.current); invincibleUntilRef.current = now + LAVA_RUNNER_CONFIG.invincibleMs; setInvincible(true); showBurst('hurt', LAVA_RUNNER_CONFIG.playerX + 4, 18); if (healthRef.current <= 0) { finish('failure'); return; } }
      }
      itemsRef.current = itemsRef.current.filter((item) => !removed.has(item.id)); setItems([...itemsRef.current]); if (resultRef.current === 'playing') frame = requestAnimationFrame(tick);
    };
    frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame);
  }, [attempt, finish, later, showBurst, showFeedback, showSpeech, startJump]);

  const progress = ((LAVA_RUNNER_CONFIG.gameDuration - timeLeft) / LAVA_RUNNER_CONFIG.gameDuration) * 100;
  const trackCycle = useMemo(() => progress < 7 ? [lavaValleyAssets.track.start, ...lavaValleyAssets.track.tiles] : progress > 94 ? [...lavaValleyAssets.track.tiles, lavaValleyAssets.track.end] : checkpointStage === 1 && progress > 42 ? [lavaValleyAssets.track.tiles[0], lavaValleyAssets.track.checkpoint, lavaValleyAssets.track.tiles[1], lavaValleyAssets.track.tiles[2]] : [...lavaValleyAssets.track.tiles, lavaValleyAssets.track.tiles[1]], [checkpointStage, progress]);
  const itemImage = (item: RunnerItem) => item.kind === 'rock' ? lavaValleyAssets.obstacles.rock : item.kind === 'geyser' ? lavaValleyAssets.obstacles.geyser : item.kind === 'coin' ? lavaValleyAssets.collectibles.coin : item.kind === 'shopItem' && item.itemId ? shopItemImages[item.itemId] : item.kind === 'shard' ? lavaValleyAssets.collectibles.rareEggShard : lavaValleyAssets.environment.checkpoint;
  const burstImage = burst ? lavaValleyAssets.effects[burst.kind === 'jump' ? 'jumpDust' : burst.kind === 'landing' ? 'landingDust' : burst.kind === 'coin' ? 'coinPickupSparkle' : burst.kind === 'item' ? 'itemPickupSparkle' : burst.kind === 'hurt' ? 'hurtImpact' : burst.kind === 'checkpoint' ? 'checkpointBurst' : 'clearBurst'] : null;
  const dashDisabled = intro || paused || result !== 'playing';
  const dashButtonImage = dashDisabled ? lavaValleyAssets.buttons.dashDisabled : dashing ? lavaValleyAssets.buttons.dashPressed : dashCooldownMs > 0 ? lavaValleyAssets.buttons.dashCooldown : lavaValleyAssets.buttons.dashReady;
  const formatTime = (seconds: number) => String(Math.floor(seconds / 60)).padStart(2, '0') + ':' + String(seconds % 60).padStart(2, '0');

  return <section className={`lava-runner ${paused ? 'lava-runner--paused' : ''} ${dashing ? 'lava-runner--dashing' : ''}`} style={{ '--lava-player-x': `${LAVA_RUNNER_CONFIG.playerX}%`, '--lava-track-bottom': `${LAVA_RUNNER_CONFIG.trackBottom}%`, '--lava-track-duration': `${2.8 * 32 / LAVA_VALLEY_DIFFICULTY[difficulty].runSpeed / (dashing ? LAVA_RUNNER_CONFIG.dashSpeedMultiplier : 1)}s`, '--lava-player-scale': LAVA_VALLEY_DIFFICULTY[difficulty].playerVisualScale, '--lava-obstacle-scale': LAVA_VALLEY_DIFFICULTY[difficulty].obstacleVisualScale } as CSSProperties}>
    <img src={lavaValleyAssets.runnerBackground} alt="용암이 흐르는 화산 계곡" className="lava-runner__background" draggable={false} /><div className="lava-runner__shade" />
    <header className="lava-runner__header"><button type="button" className="lava-runner__exit" onClick={onExit}><ChevronLeft /> 지도</button><div className="lava-runner-hud lava-panel-root"><img className="lava-panel-bg" src={lavaValleyAssets.hud.top} alt="" aria-hidden="true" /><div className="lava-panel-overlay"><span className="lava-runner-hud__health" aria-label={`하트 ${health}개`}>{[0, 1, 2].map((slot) => <i key={slot} className={slot < health ? 'is-filled' : ''}>♥</i>)}</span><b className="lava-runner-hud__coin">{coins}</b><b className="lava-runner-hud__rare">{rareShards}</b><b className="lava-runner-hud__time"><span>{formatTime(timeLeft)}</span><small>{Math.round(progress)}%</small></b></div></div><button type="button" className="lava-runner__settings" onClick={openSettings} aria-label="일시정지 및 설정"><img src={lavaValleyAssets.buttons.pauseSettings} alt="" /></button><div className="lava-runner__progress"><i style={{ width: `${progress}%` }} /><span>탐험 {checkpointStage}/2</span></div></header>
    <main className="lava-runner__playfield"><div className="lava-runner__track"><div className="lava-runner__track-strip">{[...trackCycle, ...trackCycle].map((src, index) => <img key={index} src={src} alt="" aria-hidden="true" />)}</div><img className="lava-runner__track-cracks" src={lavaValleyAssets.track.crackOverlay} alt="" aria-hidden="true" /><img className="lava-runner__track-edge" src={lavaValleyAssets.track.edgeStrip} alt="" aria-hidden="true" /></div>
      {progress < 12 && <img className="lava-runner-environment lava-runner-environment--warning" src={lavaValleyAssets.environment.warningSign} alt="장애물 주의" />}
      {items.map((item) => <div key={item.id} className={`lava-runner-item lava-runner-item--${item.kind} ${isCollectible(item.kind) && item.height === LAVA_VALLEY_COLLECTIBLE_LANES.high ? 'lava-runner-item--high' : ''}`} style={{ '--runner-x': `${item.x}%`, '--runner-y': `${item.height}%` } as CSSProperties}><img src={itemImage(item)} alt={item.kind === 'rock' ? '바위 장애물' : item.kind === 'geyser' ? '용암 분출 장애물' : item.kind === 'coin' ? '공룡 코인' : item.kind === 'shopItem' ? (item.label ?? '상점 아이템') + ' 보상' : item.kind === 'shard' ? '희귀 알 조각' : '체크포인트 깃발'} draggable={false} /></div>)}
      <LavaValleyPlayer intro={intro} invincible={invincible} jumping={jumping} jumpY={jumpY} rising={jumpVelocityRef.current >= 0} success={result === 'success'} />
      <div className="lava-runner-speed-lines" aria-hidden="true"><i /><i /><i /></div>
      <img className={`lava-runner-ground-shadow ${jumping ? 'is-jumping' : ''} ${dashing ? 'is-dashing' : ''}`} src={lavaValleyAssets.effects.dinosaurContactShadow} alt="" aria-hidden="true" />
      {burst && burstImage && <img key={burst.id} className={`lava-runner-burst lava-runner-burst--${burst.kind}`} style={{ left: `${burst.x}%`, bottom: `${burst.y}%` }} src={burstImage} alt="" aria-hidden="true" onAnimationEnd={() => setBurst((current) => current?.id === burst.id ? null : current)} />}
      {pickupFeedback && <div key={pickupFeedback.id} className={`lava-runner-pickup lava-runner-pickup--${pickupFeedback.kind}`} role="status">{pickupFeedback.label}</div>}
      {speech && <div className="lava-runner-speech lava-panel-root"><img className="lava-panel-bg" src={lavaValleyAssets.events.speechBubble} alt="" /><div className="lava-panel-overlay"><span className="lava-runner-speech__text">{speech}</span></div></div>}
      {combo && <div className="lava-runner-combo"><img src={lavaValleyAssets.events.comboPopup} alt="" /><b>3 콤보!</b></div>}
      {result === 'success' && !showResult && <div className="lava-runner-finish"><img className="lava-runner-finish__gate" src={lavaValleyAssets.environment.raceGateArch} alt="도착 지점" /><img className="lava-runner-finish__portal" src={lavaValleyAssets.environment.goalPortal} alt="클리어 포털" /><img className="lava-runner-finish__chest" src={finishStep < 2 ? lavaValleyAssets.environment.treasureChestClosed : lavaValleyAssets.environment.treasureChestOpen} alt="보물 상자" /></div>}
    </main>
    <footer className="lava-runner__controls"><button type="button" className={`lava-runner__dash ${dashing ? 'is-active' : ''}`} disabled={dashCooldownMs > 0 || dashDisabled} onPointerDown={(event) => { event.preventDefault(); dash(); }} aria-label={dashing ? '대시 중' : dashCooldownMs > 0 ? `대시 재사용까지 ${(dashCooldownMs / 1000).toFixed(1)}초` : '대시'}><img src={dashButtonImage} alt="" draggable={false} /><small aria-hidden="true">{!dashing && dashCooldownMs > 0 ? `${(dashCooldownMs / 1000).toFixed(1)}초` : ''}</small></button><button type="button" className={`lava-runner__jump ${jumpGuideActive ? 'lava-runner__jump--guide' : ''}`} onPointerDown={(event) => { event.preventDefault(); event.currentTarget.setPointerCapture(event.pointerId); setJumpPressed(true); jump(); }} onPointerUp={() => setJumpPressed(false)} onPointerCancel={() => setJumpPressed(false)} onPointerLeave={() => setJumpPressed(false)} aria-label="점프"><img src={jumpPressed ? lavaValleyAssets.buttons.jumpPressed : lavaValleyAssets.buttons.jumpNormal} alt="" /></button></footer>
    {!assetsReady && <div className="lava-runner-loading" role="status">모험 준비 중...</div>}
    {assetsReady && intro && <div className="lava-runner-intro" role="status" aria-label="용암계곡 스테이지 시작"><div><img src={lavaValleyAssets.events.levelIntro} alt="STAGE 1 용암계곡" /></div></div>}
    {paused && !externalMainModalOpen && <div className="lava-runner-modal"><section role="dialog" aria-modal="true" aria-label="용암계곡 일시정지" className="lava-runner-pause-panel"><img src={lavaValleyAssets.events.pauseMenu} alt="PAUSE" /><div><button type="button" onClick={closeSettings}>계속하기</button><button type="button" onClick={() => restartCurrentSession('manual_restart')}>처음부터</button><button type="button" onClick={onExit}>지도</button></div><fieldset><legend>난이도</legend>{([['easy','쉬움'],['normal','보통'],['challenge','도전']] as const).map(([value,label]) => <button type="button" key={value} aria-pressed={difficulty === value} onClick={() => chooseDifficulty(value)}>{label}</button>)}</fieldset></section></div>}
    {showResult && !externalMainModalOpen && <div className="lava-runner-modal lava-result-modal"><section role="dialog" aria-modal="true" aria-label={result === 'success' ? '용암계곡 탐험 완료' : '도전 실패'} className={`lava-result-panel ${result === 'failure' ? 'lava-result-panel--failure' : ''}`}>{result === 'success' ? <><div className="lava-result-panel__frame lava-panel-root"><img className="lava-panel-bg" src={lavaValleyAssets.events.resultClear} alt="CLEAR" /><div className="lava-panel-overlay lava-result-reward-overlay"><b className="lava-result-coin-value">+{committedRewards?.coins ?? 0}</b><b className="lava-result-fragment-value">+{committedRewards?.rareFragments ?? 0}</b></div></div><div className="lava-result-item-box"><strong className="lava-result-item-title">획득 아이템</strong>{committedRewards?.shopItems.length ? <div className="lava-result-item-list">{committedRewards.shopItems.slice(0, 2).map((reward) => { const item = getItemConfig(reward.itemId); return <div className="lava-result-item-row" key={reward.itemId}><img src={shopItemImages[reward.itemId]} alt="" /><span>{item?.name ?? reward.itemId}</span><b>x{reward.quantity}</b></div>; })}{committedRewards.shopItems.length > 2 && <small>외 {committedRewards.shopItems.length - 2}종</small>}</div> : <p className="lava-result-item-empty">이번 판에는 추가 아이템이 없어요</p>}</div></> : <div className="lava-result-failure-copy"><h2>아쉽다! 다시 도전해볼까?</h2><p>이번 보상은 저장되지 않았어요. 무료로 다시 연습할 수 있어요!</p></div>}<div className="lava-result-actions"><button type="button" onClick={result === 'success' ? onRetry : () => restartCurrentSession('hp_depleted')}><RotateCcw /> {result === 'success' ? '한 번 더' : '다시 도전'}</button><button type="button" onClick={onExit}>지도</button></div></section></div>}
  </section>;
}
