import { memo, useCallback, useEffect, useRef, useState, type CSSProperties } from 'react';
import { ChevronLeft, RotateCcw, X } from 'lucide-react';
import { skyIslandAssets } from '../../assets/adventure/sky-island';
import { adventureCommonAssets } from '../../assets/adventure';
import { applyHealthRestore, shouldSpawnHealthRestore } from '../../config/adventureCollectibles';
import { createRareFragmentSpawnPlan, MAX_RARE_FRAGMENTS_PER_RUN, SKY_ISLAND_DURATION_SECONDS, SKY_ISLAND_MOCK_MODE, type MinigameRunRewards, type RareFragmentSpawn } from '../../config/minigameConfig';
import { canActivateSkyBoost, resolveSkyObstacleCollision, SKY_BOOST_COOLDOWN_MS, SKY_BOOST_DURATION_MS } from '../../config/skyBoost';
import { createSkyObstacleLaneState, createSkyObstacleWave } from '../../config/skyObstacleLanes';
import { SKY_ISLAND_STAGE_CONFIG } from '../../config/adventureStages';
import { AdventureStageIntro } from '../AdventureStageIntro';
import type { OwnedDinosaur } from '../../types/game';
import { preloadImages } from '../../utils/preloadImages';

export const SKY_ISLAND_CONFIG = { gameDuration: SKY_ISLAND_DURATION_SECONDS, playerHealth: 3, playerInvincibleMs: 1200, playerX: 26, spawnX: 110, despawnX: -12, playerHitboxX: 7, playerHitboxY: 8, obstacleHitboxX: 6, obstacleHitboxY: 9, collectHitboxX: 11, collectHitboxY: 13 } as const;
export type SkyDifficulty = 'easy' | 'normal' | 'challenge';
export const SKY_DIFFICULTY = {
  easy: { level: 1, label: '쉬움', laneCount: 3, laneTransitionMs: 220, speed: 30, spawnIntervals: [[1800, 2150], [1600, 1950], [1450, 1800]], doubleBlockChances: [.08, .16, .24], playerHitboxScale: .8, obstacleHitboxScale: .88, collectHitboxScale: 1.22, extraRewardChance: .42 },
  normal: { level: 2, label: '보통', laneCount: 3, laneTransitionMs: 220, speed: 34, spawnIntervals: [[1600, 1900], [1400, 1700], [1250, 1550]], doubleBlockChances: [.18, .32, .46], playerHitboxScale: 1, obstacleHitboxScale: 1, collectHitboxScale: 1, extraRewardChance: .24 },
  challenge: { level: 3, label: '도전', laneCount: 5, laneTransitionMs: 185, speed: 40, spawnIntervals: [[1400, 1700], [1150, 1450], [1000, 1300]], doubleBlockChances: [.28, .48, .64], playerHitboxScale: 1.08, obstacleHitboxScale: 1.08, collectHitboxScale: .9, extraRewardChance: .1 },
} as const;
export const SKY_LANE_CONFIG = {
  easy: { count: 3, positions: [75, 50, 25] },
  normal: { count: 3, positions: [75, 50, 25] },
  challenge: { count: 5, positions: [85, 67.5, 50, 32.5, 15] },
} as const;
export const SKY_HUD_LAYOUT = {
  health: { left: 24, width: 12 }, coin: { left: 43, width: 12 }, fragment: { left: 62, width: 12 }, progress: { left: 81, width: 13 },
} as const;
type SkyObjectKind = 'rock' | 'cloud' | 'thorn' | 'coin' | 'fragment' | 'health_restore';
type SkyObject = { id: number; lane: number; x: number; kind: SkyObjectKind };
type Outcome = 'playing' | 'success' | 'failure';
type PatternEntry = { kind: SkyObjectKind; lane: number };
const OBSTACLES = new Set<SkyObjectKind>(['rock', 'cloud', 'thorn']);
const OBSTACLE_KINDS = ['rock', 'cloud', 'thorn'] as const;
export const getSkyLaneY = (lane: number, laneContext: SkyDifficulty | number) => { const difficulty: SkyDifficulty = typeof laneContext === 'number' ? (laneContext === 5 ? 'challenge' : 'normal') : laneContext; return SKY_LANE_CONFIG[difficulty].positions[Math.max(0, Math.min(SKY_LANE_CONFIG[difficulty].count - 1, lane))]; };
export const getSkyCollisionYThreshold = (difficulty: SkyDifficulty) => { const positions = SKY_LANE_CONFIG[difficulty].positions; const laneSpacing = Math.abs(positions[0] - positions[1]); const preset = SKY_DIFFICULTY[difficulty]; return Math.min((SKY_ISLAND_CONFIG.playerHitboxY * preset.playerHitboxScale) + (SKY_ISLAND_CONFIG.obstacleHitboxY * preset.obstacleHitboxScale), laneSpacing * .45); };
const randomBetween = (min: number, max: number) => min + Math.random() * (max - min);
const phaseIndex = (elapsedSeconds: number) => elapsedSeconds < SKY_ISLAND_CONFIG.gameDuration * .25 ? 0 : elapsedSeconds < SKY_ISLAND_CONFIG.gameDuration * (7 / 12) ? 1 : 2;
const spawnDelay = (elapsedSeconds: number, difficulty: SkyDifficulty) => { const [min, max] = SKY_DIFFICULTY[difficulty].spawnIntervals[phaseIndex(elapsedSeconds)]; return randomBetween(min, max); };

const SkyIslandPlayer = memo(function SkyIslandPlayer({ invincible, bank, outcome, started }: { invincible: boolean; bank: 'up' | 'down' | null; outcome: Outcome; started: boolean }) {
  const still = outcome === 'success' ? skyIslandAssets.player.victory : invincible ? skyIslandAssets.player.hurt : bank === 'up' ? skyIslandAssets.player.up : bank === 'down' ? skyIslandAssets.player.down : !started ? skyIslandAssets.player.idle : null;
  return <div className={`sky-runner-player ${invincible ? 'sky-runner-player--invincible' : ''} ${bank ? `sky-runner-player--bank-${bank}` : ''}`}>{still ? <img src={still} alt="프테라노돈" draggable={false} /> : <span className="sky-runner-fly-cycle">{skyIslandAssets.player.fly.map((src) => <img key={src} src={src} alt="" draggable={false} />)}</span>}</div>;
});

export interface SkyIslandPrototypeProps { dinosaur: OwnedDinosaur; onExit: () => void; runId: string; onFinishRun: (runId: string, rewards: MinigameRunRewards) => MinigameRunRewards; onRetry: () => void; externalMainModalOpen?: boolean }

export function SkyIslandPrototype({ onExit, runId, onFinishRun, onRetry, externalMainModalOpen = false }: SkyIslandPrototypeProps) {
  const [objects, setObjects] = useState<SkyObject[]>([]), [health, setHealth] = useState(3), [coins, setCoins] = useState(0), [fragments, setFragments] = useState(0), [timeLeft, setTimeLeft] = useState(SKY_ISLAND_CONFIG.gameDuration);
  const [outcome, setOutcome] = useState<Outcome>('playing'), [invincible, setInvincible] = useState(false), [paused, setPaused] = useState(false), [assetsReady, setAssetsReady] = useState(false), [tutorial, setTutorial] = useState(true), [attempt, setAttempt] = useState(0), [laneIndex, setLaneIndex] = useState(1), [difficulty, setDifficulty] = useState<SkyDifficulty>('easy'), [activeDifficulty, setActiveDifficulty] = useState<SkyDifficulty>('easy'), [bank, setBank] = useState<'up' | 'down' | null>(null);
  const [feedback, setFeedback] = useState<{ id: number; x: number; label: string; kind: 'collect' | 'hurt' } | null>(null), [committedRewards, setCommittedRewards] = useState<MinigameRunRewards | null>(null);
  const [boostActive, setBoostActive] = useState(false), [boostCooldownMs, setBoostCooldownMs] = useState(0);
  const playfieldRef = useRef<HTMLDivElement | null>(null), playerElementRef = useRef<HTMLDivElement | null>(null), objectElementsRef = useRef(new Map<number, HTMLDivElement>()), objectsRef = useRef<SkyObject[]>([]);
  const playerYRef = useRef(50), targetPlayerYRef = useRef(50), laneIndexRef = useRef(1), activeDifficultyRef = useRef<SkyDifficulty>('easy'), healthRef = useRef(3), coinsRef = useRef(0), fragmentsRef = useRef(0), outcomeRef = useRef<Outcome>('playing'), pausedRef = useRef(false), startedRef = useRef(false);
  const startTimeRef = useRef(0), lastFrameRef = useRef(0), nextSpawnRef = useRef(0), nextIdRef = useRef(1), invincibleUntilRef = useRef(0), boostActiveUntilRef = useRef(0), boostReadyAtRef = useRef(0), pauseStartedRef = useRef(0), rewardCommittedRef = useRef(false), feedbackTimerRef = useRef<number | null>(null), bankTimerRef = useRef<number | null>(null);
  const rarePlanRef = useRef<RareFragmentSpawn[]>([]), spawnedRareIdsRef = useRef(new Set<number>()), rareStatsRef = useRef({ scheduled: 0, spawned: 0, collected: 0 });
  const healthRestoreSpawnedRef = useRef(false);
  const obstacleLaneStateRef = useRef(createSkyObstacleLaneState()), obstacleLaneStatsRef = useRef<number[]>([]);

  const syncScene = useCallback(() => {
    const field = playfieldRef.current; if (!field) return;
    const width = field.clientWidth, height = field.clientHeight;
    if (playerElementRef.current) playerElementRef.current.style.transform = `translate3d(${width * SKY_ISLAND_CONFIG.playerX / 100}px,${height * playerYRef.current / 100}px,0)`;
    const laneCount = SKY_DIFFICULTY[activeDifficultyRef.current].laneCount;
    objectsRef.current.forEach((object) => { const element = objectElementsRef.current.get(object.id); if (element) element.style.transform = `translate3d(${width * object.x / 100}px,${height * getSkyLaneY(object.lane, laneCount) / 100}px,0)`; });
  }, []);
  const showFeedback = useCallback((label: string, kind: 'collect' | 'hurt') => { if (feedbackTimerRef.current) window.clearTimeout(feedbackTimerRef.current); const next = { id: nextIdRef.current++, x: SKY_ISLAND_CONFIG.playerX, label, kind }; setFeedback(next); feedbackTimerRef.current = window.setTimeout(() => setFeedback((current) => current?.id === next.id ? null : current), 520); }, []);
  const beginRun = useCallback(() => { const now = performance.now(); rarePlanRef.current = createRareFragmentSpawnPlan(activeDifficultyRef.current, SKY_ISLAND_CONFIG.gameDuration); spawnedRareIdsRef.current.clear(); rareStatsRef.current = { scheduled: rarePlanRef.current.length, spawned: 0, collected: 0 }; startedRef.current = true; startTimeRef.current = now; lastFrameRef.current = now; nextSpawnRef.current = now + 900; setTutorial(false); }, []);
  const moveLane = useCallback((direction: -1 | 1) => { if (outcomeRef.current !== 'playing' || pausedRef.current || !startedRef.current) return; const preset = SKY_DIFFICULTY[activeDifficultyRef.current], nextLane = Math.max(0, Math.min(preset.laneCount - 1, laneIndexRef.current + direction)); if (nextLane === laneIndexRef.current) return; laneIndexRef.current = nextLane; targetPlayerYRef.current = getSkyLaneY(nextLane, preset.laneCount); setLaneIndex(nextLane); setBank(direction > 0 ? 'up' : 'down'); if (bankTimerRef.current) window.clearTimeout(bankTimerRef.current); bankTimerRef.current = window.setTimeout(() => setBank(null), preset.laneTransitionMs); }, []);
  const activateBoost = useCallback(() => { const now = performance.now(); if (outcomeRef.current !== 'playing' || pausedRef.current || !startedRef.current || !canActivateSkyBoost(now, boostReadyAtRef.current)) return; boostActiveUntilRef.current = now + SKY_BOOST_DURATION_MS; boostReadyAtRef.current = now + SKY_BOOST_COOLDOWN_MS; setBoostActive(true); setBoostCooldownMs(SKY_BOOST_COOLDOWN_MS); }, []);
  const finish = useCallback((next: Exclude<Outcome, 'playing'>) => { if (outcomeRef.current !== 'playing') return; outcomeRef.current = next; objectsRef.current = []; setObjects([]); setOutcome(next); if (next === 'success' && !rewardCommittedRef.current) { rewardCommittedRef.current = true; const rewards = { coins: coinsRef.current, rareFragments: fragmentsRef.current, shopItems: [] }; setCommittedRewards(SKY_ISLAND_MOCK_MODE ? rewards : onFinishRun(runId, rewards)); } }, [onFinishRun, runId]);
  const reset = useCallback(() => { const preset = SKY_DIFFICULTY[difficulty], centerLane = Math.floor(preset.laneCount / 2), centerY = getSkyLaneY(centerLane, preset.laneCount); objectsRef.current = []; objectElementsRef.current.clear(); healthRestoreSpawnedRef.current = false; obstacleLaneStateRef.current = createSkyObstacleLaneState(); obstacleLaneStatsRef.current = []; laneIndexRef.current = centerLane; playerYRef.current = centerY; targetPlayerYRef.current = centerY; activeDifficultyRef.current = difficulty; healthRef.current = 3; coinsRef.current = 0; fragmentsRef.current = 0; outcomeRef.current = 'playing'; pausedRef.current = false; startedRef.current = false; rewardCommittedRef.current = false; invincibleUntilRef.current = 0; boostActiveUntilRef.current = 0; boostReadyAtRef.current = 0; setObjects([]); setLaneIndex(centerLane); setActiveDifficulty(difficulty); setHealth(3); setCoins(0); setFragments(0); setTimeLeft(SKY_ISLAND_CONFIG.gameDuration); setOutcome('playing'); setInvincible(false); setBoostActive(false); setBoostCooldownMs(0); setPaused(false); setTutorial(true); setFeedback(null); setCommittedRewards(null); setAttempt((value) => value + 1); }, [difficulty]);
  const openSettings = () => { if (!startedRef.current || outcomeRef.current !== 'playing') return; pauseStartedRef.current = performance.now(); pausedRef.current = true; setPaused(true); };
  const closeSettings = () => { const pausedFor = performance.now() - pauseStartedRef.current; startTimeRef.current += pausedFor; nextSpawnRef.current += pausedFor; invincibleUntilRef.current += pausedFor; if (boostActiveUntilRef.current) boostActiveUntilRef.current += pausedFor; if (boostReadyAtRef.current) boostReadyAtRef.current += pausedFor; lastFrameRef.current = performance.now(); pausedRef.current = false; setPaused(false); };

  useEffect(() => { let cancelled = false; preloadImages([...skyIslandAssets.player.fly, skyIslandAssets.player.idle, skyIslandAssets.player.up, skyIslandAssets.player.down, skyIslandAssets.player.hurt, skyIslandAssets.player.victory, ...Object.values(skyIslandAssets.background), ...Object.values(skyIslandAssets.obstacles), ...Object.values(skyIslandAssets.collectibles), ...Object.values(skyIslandAssets.ui.buttons), adventureCommonAssets.healthRestore]).then(() => { if (!cancelled) setAssetsReady(true); }).catch(console.error); return () => { cancelled = true; }; }, []);
  useEffect(() => { const down = (event: KeyboardEvent) => { if (event.repeat) return; if (event.code === 'ArrowDown') { event.preventDefault(); moveLane(-1); } if (event.code === 'ArrowUp') { event.preventDefault(); moveLane(1); } }; window.addEventListener('keydown', down); return () => window.removeEventListener('keydown', down); }, [moveLane]);
  useEffect(() => {
    let frame = 0;
    const spawn = (now: number) => { const elapsedSeconds = (now - startTimeRef.current) / 1000, selectedDifficulty = activeDifficultyRef.current, preset = SKY_DIFFICULTY[selectedDifficulty], phase = phaseIndex(elapsedSeconds); let obstacleCount = selectedDifficulty === 'challenge' ? (Math.random() < [.12, .24, .36][phase] ? 3 : 2) : (Math.random() < preset.doubleBlockChances[phase] ? 2 : 1); const obstacleLanes = createSkyObstacleWave(selectedDifficulty, preset.laneCount, obstacleCount, obstacleLaneStateRef.current); obstacleLaneStatsRef.current.push(...obstacleLanes); const occupied = new Set(obstacleLanes); const safeLanes = Array.from({ length: preset.laneCount }, (_, lane) => lane).filter((lane) => !occupied.has(lane)); const rewardLane = safeLanes[Math.floor(Math.random() * safeLanes.length)]; const entries: PatternEntry[] = obstacleLanes.map((lane, index) => ({ kind: OBSTACLE_KINDS[(nextIdRef.current + index) % OBSTACLE_KINDS.length], lane })); entries.push({ kind: 'coin', lane: rewardLane }); if (Math.random() < preset.extraRewardChance && safeLanes.length > 1) { const extraLane = safeLanes.find((lane) => lane !== rewardLane); if (extraLane !== undefined) entries.push({ kind: 'coin', lane: extraLane }); } if (shouldSpawnHealthRestore(healthRef.current, SKY_ISLAND_CONFIG.playerHealth, healthRestoreSpawnedRef.current)) { const rewardIndex = entries.findIndex((entry) => !OBSTACLES.has(entry.kind)); if (rewardIndex >= 0) { entries[rewardIndex] = { ...entries[rewardIndex], kind: 'health_restore' }; healthRestoreSpawnedRef.current = true; } } let obstacleOrder = 0; objectsRef.current = [...objectsRef.current, ...entries.map((entry) => ({ id: nextIdRef.current++, lane: entry.lane, x: SKY_ISLAND_CONFIG.spawnX + (OBSTACLES.has(entry.kind) ? obstacleOrder++ * 5 : 0), kind: entry.kind }))]; setObjects([...objectsRef.current]); nextSpawnRef.current = now + spawnDelay(elapsedSeconds, selectedDifficulty); };
    const spawnScheduledRareFragment = (elapsedSeconds: number) => { const scheduled = rarePlanRef.current.find((drop) => !spawnedRareIdsRef.current.has(drop.id) && elapsedSeconds >= drop.spawnAtSeconds); if (!scheduled || objectsRef.current.some((object) => object.x > 76)) return; const laneCount = SKY_DIFFICULTY[activeDifficultyRef.current].laneCount; const occupied = new Set(objectsRef.current.filter((object) => object.x > 58).map((object) => object.lane)); const safeLanes = Array.from({ length: laneCount }, (_, lane) => lane).filter((lane) => !occupied.has(lane)); if (!safeLanes.length) return; const lane = safeLanes[Math.floor(Math.random() * safeLanes.length)]; spawnedRareIdsRef.current.add(scheduled.id); rareStatsRef.current.spawned += 1; objectsRef.current.push({ id: nextIdRef.current++, lane, x: SKY_ISLAND_CONFIG.spawnX, kind: 'fragment' }); setObjects([...objectsRef.current]); };
    const tick = (now: number) => {
      if (!startedRef.current || pausedRef.current || outcomeRef.current !== 'playing') { lastFrameRef.current = now; syncScene(); frame = requestAnimationFrame(tick); return; }
      const delta = Math.min((now - (lastFrameRef.current || now)) / 1000, .04); lastFrameRef.current = now;
      const distanceToTarget = targetPlayerYRef.current - playerYRef.current;
      const movementPreset = SKY_DIFFICULTY[activeDifficultyRef.current], laneDistance = Math.abs(getSkyLaneY(0, movementPreset.laneCount) - getSkyLaneY(1, movementPreset.laneCount));
      const maxLaneStep = laneDistance * (1000 / movementPreset.laneTransitionMs) * delta;
      playerYRef.current += Math.sign(distanceToTarget) * Math.min(Math.abs(distanceToTarget), maxLaneStep);
      const remaining = Math.max(0, Math.ceil(SKY_ISLAND_CONFIG.gameDuration - (now - startTimeRef.current) / 1000)); setTimeLeft((current) => current === remaining ? current : remaining); if (!remaining) { finish('success'); return; }
      const nextBoostActive = now < boostActiveUntilRef.current, nextBoostCooldown = Math.max(0, boostReadyAtRef.current - now); setBoostActive((current) => current === nextBoostActive ? current : nextBoostActive); setBoostCooldownMs((current) => Math.ceil(current / 100) === Math.ceil(nextBoostCooldown / 100) ? current : nextBoostCooldown);
      if (now >= nextSpawnRef.current) spawn(now);
      spawnScheduledRareFragment((now - startTimeRef.current) / 1000);
      const removed = new Set<number>();
      const difficultyPreset = SKY_DIFFICULTY[activeDifficultyRef.current];
      for (const object of objectsRef.current) {
        object.x -= difficultyPreset.speed * delta; if (object.x < SKY_ISLAND_CONFIG.despawnX) { removed.add(object.id); continue; }
        const distanceX = Math.abs(object.x - SKY_ISLAND_CONFIG.playerX), distanceY = Math.abs(getSkyLaneY(object.lane, difficultyPreset.laneCount) - playerYRef.current);
        const playerHitboxX = SKY_ISLAND_CONFIG.playerHitboxX * difficultyPreset.playerHitboxScale, obstacleHitboxX = SKY_ISLAND_CONFIG.obstacleHitboxX * difficultyPreset.obstacleHitboxScale, collisionYThreshold = getSkyCollisionYThreshold(activeDifficultyRef.current);
        if (OBSTACLES.has(object.kind) && distanceX <= playerHitboxX + obstacleHitboxX && distanceY <= collisionYThreshold && now >= invincibleUntilRef.current) { removed.add(object.id); const collision = resolveSkyObstacleCollision(now < boostActiveUntilRef.current); if (collision.consumeBoost) { boostActiveUntilRef.current = 0; setBoostActive(false); showFeedback('바람 방패!', 'collect'); } else { healthRef.current -= collision.damage; setHealth(healthRef.current); invincibleUntilRef.current = now + SKY_ISLAND_CONFIG.playerInvincibleMs; setInvincible(true); showFeedback('앗!', 'hurt'); if (healthRef.current <= 0) { finish('failure'); break; } } }
        else if (!OBSTACLES.has(object.kind) && distanceX <= SKY_ISLAND_CONFIG.collectHitboxX * difficultyPreset.collectHitboxScale && distanceY <= SKY_ISLAND_CONFIG.collectHitboxY * difficultyPreset.collectHitboxScale) { removed.add(object.id); if (object.kind === 'coin') { coinsRef.current += 1; setCoins(coinsRef.current); showFeedback('+1', 'collect'); } if (object.kind === 'fragment' && fragmentsRef.current < MAX_RARE_FRAGMENTS_PER_RUN) { fragmentsRef.current += 1; rareStatsRef.current.collected += 1; setFragments(fragmentsRef.current); showFeedback('조각 +1', 'collect'); } if (object.kind === 'health_restore') { healthRef.current = applyHealthRestore(healthRef.current, SKY_ISLAND_CONFIG.playerHealth); setHealth(healthRef.current); showFeedback('생명력 +1', 'collect'); } }
      }
      const nextInvincible = now < invincibleUntilRef.current; setInvincible((current) => current === nextInvincible ? current : nextInvincible);
      if (removed.size && outcomeRef.current === 'playing') { objectsRef.current = objectsRef.current.filter((object) => !removed.has(object.id)); setObjects([...objectsRef.current]); }
      syncScene(); if (outcomeRef.current === 'playing') frame = requestAnimationFrame(tick);
    };
    frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame);
  }, [attempt, finish, showFeedback, syncScene]);
  useEffect(() => () => { if (feedbackTimerRef.current) window.clearTimeout(feedbackTimerRef.current); if (bankTimerRef.current) window.clearTimeout(bankTimerRef.current); }, []);
  useEffect(() => { if (import.meta.env.DEV && outcome !== 'playing') { const lanes = obstacleLaneStatsRef.current, laneCount = SKY_DIFFICULTY[activeDifficultyRef.current].laneCount, usage = Array.from({ length: laneCount }, (_, lane) => lanes.filter((value) => value === lane).length), repeats = lanes.filter((lane, index) => index > 0 && lane === lanes[index - 1]).length, averageDelta = lanes.length > 1 ? lanes.slice(1).reduce((sum, lane, index) => sum + Math.abs(lane - lanes[index]), 0) / (lanes.length - 1) : 0; console.debug('[Sky Island] rare fragments', rareStatsRef.current); console.debug('[Sky Island] obstacle lanes', { sequence: lanes.join(','), usage, sameLaneRepeatRate: lanes.length > 1 ? repeats / (lanes.length - 1) : 0, averageLaneDelta: averageDelta }); } }, [outcome]);

  const obstacleImages = [skyIslandAssets.obstacles.flyingRock, skyIslandAssets.obstacles.lightningCloud, skyIslandAssets.obstacles.spikeCloud];
  const objectContent = (object: SkyObject) => <img src={OBSTACLES.has(object.kind) ? obstacleImages[object.id % obstacleImages.length] : object.kind === 'health_restore' ? adventureCommonAssets.healthRestore : object.kind === 'fragment' ? skyIslandAssets.collectibles.rareFragment : skyIslandAssets.collectibles.coin} alt={object.kind === 'coin' ? '코인' : object.kind === 'fragment' ? '희귀조각' : object.kind === 'health_restore' ? '생명력 회복' : '비행 장애물'} />;
  const progress = (SKY_ISLAND_CONFIG.gameDuration - timeLeft) / SKY_ISLAND_CONFIG.gameDuration * 100;
  return <section className={`sky-island-game sky-runner ${paused ? 'sky-runner--paused' : ''}`}><header className="sky-runner-hud"><button type="button" onClick={onExit} className="sky-exit"><ChevronLeft /> 지도</button><div className="sky-runner-hud__panel-wrap"><img className="sky-runner-hud__panel" src={skyIslandAssets.ui.hud.top} alt="" /><div className="sky-hud-slot sky-hud-slot--health">{[0,1,2].map((heart) => <i key={heart} className={heart < health ? 'is-filled' : ''}>♥</i>)}</div><div className="sky-hud-slot sky-hud-slot--coin">{coins}</div><div className="sky-hud-slot sky-hud-slot--fragment">{fragments}</div><div className="sky-hud-slot sky-hud-slot--progress"><b>{timeLeft}초</b><small>{Math.round(progress)}%</small></div></div><button type="button" className="sky-settings-button" onClick={openSettings} aria-label="일시정지"><img src={skyIslandAssets.ui.buttons.pause} alt="" /></button></header>
    <div className="sky-runner-playfield" ref={playfieldRef}><div className="sky-runner-parallax" aria-hidden="true">{Object.values(skyIslandAssets.background).map((src, index) => <img key={src} className={`sky-runner-bg sky-runner-bg--${index}`} src={src} alt="" />)}</div><img className="sky-runner-cloud-lanes" src={skyIslandAssets.environment.cloudLane} alt="" aria-hidden="true" /><div className="sky-runner-lane-guides" aria-hidden="true">{Array.from({ length: SKY_DIFFICULTY[activeDifficulty].laneCount }, (_, lane) => <i key={lane} style={{ '--lane-y': `${getSkyLaneY(lane, SKY_DIFFICULTY[activeDifficulty].laneCount)}%` } as CSSProperties} />)}</div>{objects.map((object) => <div key={object.id} ref={(element) => { if (element) objectElementsRef.current.set(object.id, element); else objectElementsRef.current.delete(object.id); }} className={`sky-runner-object sky-runner-object--${object.kind}`}>{objectContent(object)}</div>)}<div ref={playerElementRef} className={`sky-runner-player-anchor ${boostActive ? 'sky-runner-player-anchor--boosted' : ''}`} data-lane={laneIndex}>{boostActive && <><span className="sky-boost-aura" aria-hidden="true" /><img className="sky-boost-speed-lines" src={skyIslandAssets.effects.speedLines} alt="" aria-hidden="true" /></>}<SkyIslandPlayer invincible={invincible} bank={bank} outcome={outcome} started={!tutorial} /></div>{feedback && <div key={feedback.id} className={`sky-runner-feedback sky-runner-feedback--${feedback.kind}`} style={{ '--feedback-x': `${feedback.x}%` } as CSSProperties}>{feedback.label}</div>}</div>
    <footer className="sky-runner-controls"><div className="sky-runner-control-cluster"><button type="button" className={`sky-boost-button ${boostActive ? 'is-active' : boostCooldownMs > 0 ? 'is-cooldown' : 'is-ready'}`} disabled={boostActive || boostCooldownMs > 0 || paused || tutorial || outcome !== 'playing'} onPointerDown={(event) => { event.preventDefault(); activateBoost(); }} aria-label={boostActive ? '바람 방패 사용 중' : boostCooldownMs > 0 ? `부스트 ${Math.ceil(boostCooldownMs / 1000)}초 후 사용 가능` : '바람 부스트 사용'}><img src={skyIslandAssets.ui.buttons.boost} alt="" /><span>{boostActive ? '방패!' : boostCooldownMs > 0 ? Math.ceil(boostCooldownMs / 1000) : 'BOOST'}</span></button><div className="sky-runner-paddle" aria-label="비행 높이 조절">{([[1,skyIslandAssets.ui.buttons.moveUp,'위'],[-1,skyIslandAssets.ui.buttons.moveDown,'아래']] as const).map(([direction,image,label]) => <button key={direction} type="button" onPointerDown={(event) => { event.preventDefault(); moveLane(direction); }} aria-label={`${label}로 한 칸 이동`}><img src={image} alt="" /></button>)}</div></div></footer>
    {!assetsReady && <div className="sky-runner-overlay" role="status">하늘 모험 준비 중...</div>}{assetsReady && tutorial && <AdventureStageIntro config={SKY_ISLAND_STAGE_CONFIG} onStart={beginRun} />}
    {paused && !externalMainModalOpen && <div className="sky-settings-backdrop"><section className="sky-settings-panel"><div className="sky-settings-heading"><h2>잠깐 쉬어요</h2><button type="button" onClick={closeSettings}><X /></button></div><fieldset><legend>난이도 · 다음 판부터 적용</legend>{([['easy','1단계 쉬움'],['normal','2단계 보통'],['challenge','3단계 도전']] as const).map(([value,label]) => <button type="button" key={value} aria-pressed={difficulty === value} onClick={() => setDifficulty(value)}><i /><span><b>{label}</b><small>{value === 'easy' ? '천천히, 보물은 넉넉하게' : value === 'normal' ? '조금 빠르고 다양한 길' : '5개의 비행 길이 열려요!'}</small></span></button>)}</fieldset>{difficulty !== activeDifficulty && <p className="sky-settings-pending">선택한 난이도는 다음 판부터 적용돼요.</p>}<button type="button" className="sky-settings-resume" onClick={closeSettings}>계속하기</button><button type="button" className="sky-settings-resume" onClick={reset}>처음부터</button><button type="button" className="sky-settings-resume" onClick={onExit}>지도</button></section></div>}
    {outcome !== 'playing' && !externalMainModalOpen && <div className="sky-modal"><section><div className="sky-modal-stars">{outcome === 'success' ? '⭐ ✨ ⭐' : '☁️ 🦅 ☁️'}</div><h2>{outcome === 'success' ? '하늘섬 완료!' : '다시 날아볼까요?'}</h2>{outcome === 'success' ? <div className="sky-runner-result"><span>🪙 +{committedRewards?.coins ?? 0}</span><span>💎 +{committedRewards?.rareFragments ?? 0}</span></div> : <p>보상은 저장되지 않았어요. 무료로 다시 해요!</p>}<div><button type="button" onClick={outcome === 'success' ? onRetry : reset}><RotateCcw /> {outcome === 'success' ? '한 번 더' : '무료 재도전'}</button><button type="button" onClick={onExit}>지도</button></div></section></div>}
  </section>;
}
