import { memo, useCallback, useEffect, useMemo, useRef, useState, type CSSProperties } from 'react';
import { ChevronLeft, Gem, RotateCcw, X } from 'lucide-react';
import { skyIslandAssets } from '../../assets/adventure/sky-island';
import { adventureCommonAssets } from '../../assets/adventure';
import { lavaValleyStage3Assets } from '../../assets/adventure/lava-valley';
import { applyHealthRestore, shouldSpawnHealthRestore } from '../../config/adventureCollectibles';
import { MAX_RARE_FRAGMENTS_PER_RUN, type MinigameRunRewards } from '../../config/minigameConfig';
import { canActivateSkyBoost, getSkyLightningInterval, getSkyLightningRenderX, getSkyLightningTargetLanes, resolveSkyObstacleCollision, SKY_BOOST_COOLDOWN_MS, SKY_BOOST_DURATION_MS, SKY_LIGHTNING_GAMEPLAY_ENABLED, SKY_LIGHTNING_IMPACT_MS, SKY_LIGHTNING_STRIKE_MS, SKY_LIGHTNING_TRIGGER_DISTANCE_PX, SKY_LIGHTNING_WARNING_MS } from '../../config/skyBoost';
import { createSkyBirdPattern } from '../../config/skyBirdPatterns';
import { getSkyStormRockMotion, getSkyStormRockTrackingY, SKY_STAGE_3_NORMAL_DANGER_REST_MS, SKY_STAGE_3_NORMAL_INTERVAL_MULTIPLIER, SKY_STAGE_3_NORMAL_SEQUENCE_GAP, SKY_STORM_ROCK_SPAWN_CHANCE, SKY_STORM_ROCK_SPEED_MULTIPLIER, SKY_STORM_ROCK_TRACKING_STRENGTH, SKY_STORM_ROCK_WAVE_AMPLITUDE } from '../../config/skyStormRock';
import { findSkySafeCollectibleSpawn } from '../../config/skySpawnSafety';
import { playSound } from '../../audio/audioManager';
import { createSkyObstacleLaneState, createSkyObstacleWave } from '../../config/skyObstacleLanes';
import { getAdventureStage, type AdventureStageNumber } from '../../config/adventureStageCatalog';
import { getDifficultyStorageKey, isAdventureDifficultyUnlocked, SKY_FOSSIL_OPPORTUNITY_CHANCE, SKY_ISLAND_ECONOMY, type AdventureDifficulty } from '../../config/adventureMinigameEconomy';
import { SKY_ISLAND_STAGE_CONFIG } from '../../config/adventureStages';
import { AdventureStageIntro } from '../AdventureStageIntro';
import { AdventureFinalTreasure, type AdventureFinalTreasurePhase } from '../AdventureFinalTreasure';
import type { OwnedDinosaur } from '../../types/game';
import { preloadImages } from '../../utils/preloadImages';

export const SKY_ISLAND_CONFIG = { playerHealth: 3, playerInvincibleMs: 1200, playerX: 26, spawnX: 110, despawnX: -12, playerHitboxX: 7, playerHitboxY: 8, obstacleHitboxX: 6, obstacleHitboxY: 9, collectHitboxX: 11, collectHitboxY: 13 } as const;
export type SkyDifficulty = AdventureDifficulty;
export const SKY_DIFFICULTY = {
  normal: { laneTransitionMs: 220, speed: 32, birdSpeed: 52, spawnIntervals: [[1800, 2150], [1550, 1900], [1350, 1700]], playerHitboxScale: .9, obstacleHitboxScale: .92, collectHitboxScale: 1.12 },
  hard: { laneTransitionMs: 205, speed: 36, birdSpeed: 60, spawnIntervals: [[1550, 1900], [1300, 1650], [1120, 1450]], playerHitboxScale: 1, obstacleHitboxScale: 1, collectHitboxScale: 1 },
} as const;
export const SKY_LANE_CONFIG = { 3: [75, 50, 25], 5: [85, 67.5, 50, 32.5, 15] } as const;
export const SKY_HUD_LAYOUT = { health: { left: 24, width: 12 }, coin: { left: 43, width: 12 }, fragment: { left: 62, width: 12 }, progress: { left: 81, width: 13 } } as const;
export const getSkyLaneY = (lane: number, laneCount: number) => { const positions = laneCount === 5 ? SKY_LANE_CONFIG[5] : SKY_LANE_CONFIG[3]; return positions[Math.max(0, Math.min(positions.length - 1, lane))]; };
export const getSkyCollisionYThreshold = (difficulty: SkyDifficulty, laneCount = 3) => { const positions = laneCount === 5 ? SKY_LANE_CONFIG[5] : SKY_LANE_CONFIG[3]; const spacing = Math.abs(positions[0] - positions[1]); const preset = SKY_DIFFICULTY[difficulty]; return Math.min(SKY_ISLAND_CONFIG.playerHitboxY * preset.playerHitboxScale + SKY_ISLAND_CONFIG.obstacleHitboxY * preset.obstacleHitboxScale, spacing * .45); };

type Outcome = 'playing' | 'treasure' | 'success' | 'failure';
type SkyKind = 'rock' | 'stormRock' | 'cloud' | 'thorn' | 'coin' | 'fragment' | 'health_restore' | 'fossil' | 'bird' | 'lightning';
type SkyObject = { id: number; lane: number; x: number; kind: SkyKind; phase?: 'idle' | 'warning' | 'striking' | 'done'; phaseStartedAt?: number; strikeTargetLanes?: number[]; motionStartedAt?: number; waveAmplitude?: number };
const OBSTACLES = new Set<SkyKind>(['rock', 'stormRock', 'cloud', 'thorn', 'bird']);
const randomBetween = (min: number, max: number) => min + Math.random() * (max - min);

const SkyIslandPlayer = memo(function SkyIslandPlayer({ invincible, bank, outcome, started }: { invincible: boolean; bank: 'up' | 'down' | null; outcome: Outcome; started: boolean }) {
  const still = outcome === 'success' ? skyIslandAssets.player.victory : outcome === 'failure' || invincible ? skyIslandAssets.player.hurt : !started ? skyIslandAssets.player.idle : bank === 'up' ? skyIslandAssets.player.up : bank === 'down' ? skyIslandAssets.player.down : null;
  return <div className={`sky-runner-player ${invincible ? 'sky-runner-player--invincible' : ''} ${bank ? `sky-runner-player--bank-${bank}` : ''}`}>{still ? <img src={still} alt="프테라노돈" draggable={false} /> : <span className="sky-runner-fly-cycle">{skyIslandAssets.player.fly.map(src => <img key={src} src={src} alt="" draggable={false} />)}</span>}</div>;
});

export interface SkyIslandPrototypeProps { stageNumber?: AdventureStageNumber; dinosaur: OwnedDinosaur; onExit: () => void; runId: string; onFinishRun: (runId: string, rewards: MinigameRunRewards) => MinigameRunRewards; onRetry: (retryAfterFailure?: boolean) => void; relicPartCount?: number; fossilFragmentIds?: number[]; externalMainModalOpen?: boolean }

export function SkyIslandPrototype({ stageNumber = 1, onExit, runId, onFinishRun, onRetry, relicPartCount = 0, fossilFragmentIds = [], externalMainModalOpen = false }: SkyIslandPrototypeProps) {
  const stage = getAdventureStage('skyIsland', stageNumber), duration = stage.playTime, laneCount = stageNumber === 1 ? 3 : 5;
  const storedDifficulty = useMemo<SkyDifficulty>(() => { const saved = window.localStorage.getItem(getDifficultyStorageKey('skyIsland', stageNumber)); return saved === 'hard' && isAdventureDifficultyUnlocked('skyIsland', stageNumber, 'hard', relicPartCount) ? 'hard' : 'normal'; }, [relicPartCount, stageNumber]);
  const [difficulty, setDifficulty] = useState<SkyDifficulty>(storedDifficulty), [objects, setObjects] = useState<SkyObject[]>([]), [health, setHealth] = useState(3), [coins, setCoins] = useState(0), [fragments, setFragments] = useState(0), [fossils, setFossils] = useState<number[]>(fossilFragmentIds);
  const [timeLeft, setTimeLeft] = useState(duration), [outcome, setOutcome] = useState<Outcome>('playing'), [treasurePhase, setTreasurePhase] = useState<AdventureFinalTreasurePhase>('hidden'), [paused, setPaused] = useState(false), [tutorial, setTutorial] = useState(true), [assetsReady, setAssetsReady] = useState(false), [laneIndex, setLaneIndex] = useState(Math.floor(laneCount / 2)), [bank, setBank] = useState<'up' | 'down' | null>(null), [boostActive, setBoostActive] = useState(false), [boostCooldownMs, setBoostCooldownMs] = useState(0), [committedRewards, setCommittedRewards] = useState<MinigameRunRewards | null>(null), [progress, setProgress] = useState(0), [invincible, setInvincible] = useState(false);
  const playfieldRef = useRef<HTMLDivElement>(null), playerRef = useRef<HTMLDivElement>(null), elementRefs = useRef(new Map<number, HTMLDivElement>()), objectsRef = useRef<SkyObject[]>([]), healthRef = useRef(3), coinsRef = useRef(0), fragmentsRef = useRef(0), fossilsRef = useRef(fossilFragmentIds), laneRef = useRef(Math.floor(laneCount / 2)), playerYRef = useRef(getSkyLaneY(laneRef.current, laneCount)), targetYRef = useRef(playerYRef.current), startRef = useRef(0), lastRef = useRef(0), nextSpawnRef = useRef(0), startedRef = useRef(false), pausedRef = useRef(false), outcomeRef = useRef<Outcome>('playing'), nextId = useRef(1), invincibleUntil = useRef(0), boostUntil = useRef(0), boostReadyAt = useRef(0), rewardCommitted = useRef(false), fossilSpawned = useRef(false), fossilOpportunityRef = useRef(false), rareSpawnAt = useRef<number | null>(null), rareSpawned = useRef(false), healthSpawned = useRef(false), laneState = useRef(createSkyObstacleLaneState());
  const nextLightningRef = useRef(0);
  const intro = useMemo(() => ({ ...SKY_ISLAND_STAGE_CONFIG, stage: stageNumber, title: stage.name, instruction: stageNumber === 1 ? '3개의 비행 길에서 조작을 익혀요!' : stageNumber === 2 ? '5개의 길을 읽고 화석조각을 찾아요!' : '폭풍을 피해 화석과 하늘 유물을 찾아요!' }), [stage.name, stageNumber]);
  const background = skyIslandAssets.stageBackgrounds[stageNumber];
  const sync = useCallback(() => { const field = playfieldRef.current; if (!field) return; const width = field.clientWidth, height = field.clientHeight, now = performance.now(); if (playerRef.current) playerRef.current.style.transform = `translate3d(${width * SKY_ISLAND_CONFIG.playerX / 100}px,${height * playerYRef.current / 100}px,0)`; objectsRef.current.forEach(object => { const el = elementRefs.current.get(object.id), renderX = object.kind === 'lightning' ? getSkyLightningRenderX(object.x, object.phase, SKY_ISLAND_CONFIG.playerX) : object.x, motion = object.kind === 'stormRock' ? getSkyStormRockMotion(now - (object.motionStartedAt ?? now), object.id, object.waveAmplitude ?? 8) : null, laneY = getSkyLaneY(object.lane, laneCount), trackedY = object.kind === 'stormRock' ? getSkyStormRockTrackingY(laneY, playerYRef.current, object.x, 130, SKY_ISLAND_CONFIG.playerX, SKY_STORM_ROCK_TRACKING_STRENGTH[difficulty]) : laneY, renderY = trackedY + (motion?.yOffset ?? 0); if (el) el.style.transform = `translate3d(${width * renderX / 100}px,${height * renderY / 100}px,0) rotate(${motion?.rotation ?? 0}deg)`; }); }, [difficulty, laneCount]);
  const finish = useCallback((result: 'success' | 'failure') => { if (outcomeRef.current !== 'playing') return; startedRef.current = false; if (result === 'success' && stageNumber === 3) { outcomeRef.current = 'treasure'; setOutcome('treasure'); setTreasurePhase('closed'); return; } outcomeRef.current = result; setOutcome(result); if (result === 'success' && !rewardCommitted.current) { rewardCommitted.current = true; setCommittedRewards(onFinishRun(runId, { coins: 0, runCoins: coinsRef.current, rareFragments: fragmentsRef.current, shopItems: [], fossilFragmentIds: fossilsRef.current })); } }, [onFinishRun, runId, stageNumber]);
  const openFinalTreasure = useCallback(() => { if (outcomeRef.current !== 'treasure' || treasurePhase !== 'closed' || rewardCommitted.current) return; rewardCommitted.current = true; setTreasurePhase('opening'); const rewards = onFinishRun(runId, { coins: 0, runCoins: coinsRef.current, rareFragments: fragmentsRef.current, shopItems: [], fossilFragmentIds: fossilsRef.current, finalChestBonus: { coins: 0, rareFragments: 0, shopItems: [] } }); setCommittedRewards(rewards); window.setTimeout(() => setTreasurePhase('open'), 500); window.setTimeout(() => { outcomeRef.current = 'success'; setOutcome('success'); }, 1500); }, [onFinishRun, runId, treasurePhase]);
  const beginRun = useCallback(() => { const now = performance.now(); startedRef.current = true; startRef.current = now; lastRef.current = now; nextSpawnRef.current = now + 1000; nextLightningRef.current = now + getSkyLightningInterval(stageNumber, difficulty); fossilOpportunityRef.current = !fossilsRef.current.includes(stageNumber) && Math.random() < SKY_FOSSIL_OPPORTUNITY_CHANCE[stageNumber][difficulty]; const rate = SKY_ISLAND_ECONOMY.rareFragmentDropRate[stageNumber][difficulty]; rareSpawnAt.current = Math.random() < rate ? duration * randomBetween(.35, .82) : null; setTutorial(false); }, [difficulty, duration, stageNumber]);
  const chooseDifficulty = (value: SkyDifficulty) => { if (!isAdventureDifficultyUnlocked('skyIsland', stageNumber, value, relicPartCount)) return; setDifficulty(value); window.localStorage.setItem(getDifficultyStorageKey('skyIsland', stageNumber), value); };
  const moveLane = (direction: -1 | 1) => { if (!startedRef.current || pausedRef.current) return; const next = Math.max(0, Math.min(laneCount - 1, laneRef.current + direction)); if (next === laneRef.current) return; laneRef.current = next; targetYRef.current = getSkyLaneY(next, laneCount); setLaneIndex(next); setBank(direction > 0 ? 'up' : 'down'); window.setTimeout(() => setBank(null), SKY_DIFFICULTY[difficulty].laneTransitionMs); };
  const activateBoost = () => { const now = performance.now(); if (!canActivateSkyBoost(now, boostReadyAt.current) || !startedRef.current) return; boostUntil.current = now + SKY_BOOST_DURATION_MS; boostReadyAt.current = now + SKY_BOOST_COOLDOWN_MS; setBoostActive(true); playSound('item_use'); };
  useEffect(() => { let cancelled = false; preloadImages([background, ...skyIslandAssets.player.fly, ...Object.values(skyIslandAssets.obstacles).flat(), skyIslandAssets.collectibles.coin, skyIslandAssets.collectibles.rareFragment, lavaValleyStage3Assets.treasureChestClosed, lavaValleyStage3Assets.treasureChestOpen, lavaValleyStage3Assets.treasureOpenEffect]).then(() => { if (!cancelled) setAssetsReady(true); }).catch(console.error); return () => { cancelled = true; }; }, [background]);
  useEffect(() => { let frame = 0; const tick = (now: number) => { if (!startedRef.current || pausedRef.current || outcomeRef.current !== 'playing') { lastRef.current = now; sync(); frame = requestAnimationFrame(tick); return; } const delta = Math.min((now - lastRef.current) / 1000, .04); lastRef.current = now; const elapsed = (now - startRef.current) / 1000, ratio = Math.min(1, elapsed / duration), basePreset = SKY_DIFFICULTY[difficulty], preset = stageNumber === 3 && difficulty === 'normal' ? { ...basePreset, speed: basePreset.speed * SKY_STORM_ROCK_SPEED_MULTIPLIER.normal / 1.08 } : basePreset; setProgress(ratio); setTimeLeft(Math.max(0, Math.ceil(duration - elapsed))); if (ratio >= 1) { finish('success'); return; }
      if (SKY_LIGHTNING_GAMEPLAY_ENABLED && now >= nextLightningRef.current && !objectsRef.current.some(object => object.kind === 'lightning')) { const cloudLane = Math.floor(Math.random() * laneCount); objectsRef.current.push({ id: nextId.current++, lane: cloudLane, x: SKY_ISLAND_CONFIG.spawnX, kind: 'lightning', phase: 'idle', strikeTargetLanes: getSkyLightningTargetLanes(stageNumber, difficulty, cloudLane, laneCount) }); setObjects([...objectsRef.current]); nextLightningRef.current = now + getSkyLightningInterval(stageNumber, difficulty); }
      const step = Math.abs(getSkyLaneY(0, laneCount) - getSkyLaneY(1, laneCount)) * (1000 / preset.laneTransitionMs) * delta; playerYRef.current += Math.sign(targetYRef.current - playerYRef.current) * Math.min(Math.abs(targetYRef.current - playerYRef.current), step);
      if (now >= nextSpawnRef.current) { const phase = ratio < .3 ? 0 : ratio < .65 ? 1 : 2, blockCount = stageNumber === 1 ? 1 : stageNumber === 2 ? (Math.random() < .65 ? 2 : 1) : (Math.random() < (difficulty === 'hard' ? .72 : .52) ? 3 : 2); const lanes = createSkyObstacleWave(laneCount === 5 ? 'challenge' : 'normal', laneCount, Math.min(blockCount, laneCount - 1), laneState.current); const kinds: SkyKind[] = ['rock', 'cloud', 'thorn']; const birdPattern = createSkyBirdPattern(stageNumber, difficulty, laneCount), spawnStormRock = stageNumber === 3 && Math.random() < SKY_STORM_ROCK_SPAWN_CHANCE[difficulty], fixedKind = stageNumber === 3 ? kinds[Math.floor(Math.random() * kinds.length)] : null; const additions = birdPattern && spawnStormRock ? [] : lanes.map((lane, index): SkyObject => ({ id: nextId.current++, lane, x: SKY_ISLAND_CONFIG.spawnX + index * 4, kind: fixedKind ?? kinds[(nextId.current + index) % kinds.length] })); const birdGap = stageNumber === 3 && difficulty === 'normal' ? SKY_STAGE_3_NORMAL_SEQUENCE_GAP : 12; birdPattern?.lanes.forEach((lane, index) => additions.push({ id: nextId.current++, lane, x: 122 + index * birdGap, kind: 'bird' })); if (spawnStormRock) { const stormCount = difficulty === 'hard' && Math.random() < .3 ? 2 : 1, startLane = Math.floor(Math.random() * laneCount); for (let index = 0; index < stormCount; index += 1) additions.push({ id: nextId.current++, lane: Math.max(0, Math.min(laneCount - 1, startLane + (index % 2 === 0 ? 0 : startLane < laneCount / 2 ? 2 : -2))), x: 130 + index * 11, kind: 'stormRock', motionStartedAt: now, waveAmplitude: SKY_STORM_ROCK_WAVE_AMPLITUDE[difficulty] }); } const safe = Array.from({ length: laneCount }, (_, lane) => lane).filter(lane => !lanes.includes(lane)), preferredCoinLane = safe[Math.floor(Math.random() * safe.length)] ?? Math.floor(Math.random() * laneCount), coinSpawn = findSkySafeCollectibleSpawn(preferredCoinLane, laneCount, 116, additions.filter(object => OBSTACLES.has(object.kind)).map(object => ({ lane: object.lane, x: object.x, obstacle: true }))); additions.push({ id: nextId.current++, lane: coinSpawn.lane, x: coinSpawn.x, kind: 'coin' }); objectsRef.current.push(...additions); setObjects([...objectsRef.current]); const [min,max] = preset.spawnIntervals[phase], intervalMultiplier = stageNumber === 3 && difficulty === 'normal' ? SKY_STAGE_3_NORMAL_INTERVAL_MULTIPLIER : 1, dangerRest = stageNumber === 3 && difficulty === 'normal' && (birdPattern || spawnStormRock) ? SKY_STAGE_3_NORMAL_DANGER_REST_MS : 0; nextSpawnRef.current = now + randomBetween(min,max) * intervalMultiplier + dangerRest; }
      const fossilId = stageNumber; if (fossilOpportunityRef.current && !fossilSpawned.current && !fossilsRef.current.includes(fossilId) && ratio >= SKY_ISLAND_ECONOMY.fossilFragmentRules.stages[stageNumber][0].at / 100) { fossilSpawned.current = true; objectsRef.current.push({ id: nextId.current++, lane: stageNumber === 1 ? Math.floor(laneCount / 2) : stageNumber === 2 ? (laneRef.current + 2) % laneCount : laneCount - 1, x: 108, kind: 'fossil' }); setObjects([...objectsRef.current]); }
      if (!rareSpawned.current && rareSpawnAt.current !== null && elapsed >= rareSpawnAt.current) { rareSpawned.current = true; objectsRef.current.push({ id: nextId.current++, lane: Math.floor(Math.random() * laneCount), x: 108, kind: 'fragment' }); setObjects([...objectsRef.current]); }
      const removed = new Set<number>(); for (const object of objectsRef.current) { if (object.kind === 'lightning') { if (object.phase === 'idle') { object.x -= preset.speed * delta; const fieldWidth = playfieldRef.current?.clientWidth ?? 0, distanceToPlayerPx = (object.x - SKY_ISLAND_CONFIG.playerX) * fieldWidth / 100; if (fieldWidth > 0 && distanceToPlayerPx <= SKY_LIGHTNING_TRIGGER_DISTANCE_PX && distanceToPlayerPx >= 0) { object.phase = 'warning'; object.phaseStartedAt = now; } else if (object.x < SKY_ISLAND_CONFIG.despawnX) removed.add(object.id); } else { const phaseAge = now - (object.phaseStartedAt ?? now); if (object.phase === 'warning' && phaseAge >= SKY_LIGHTNING_WARNING_MS) { object.phase = 'striking'; object.phaseStartedAt = now; } else if (object.phase === 'striking') { if ((object.strikeTargetLanes ?? [object.lane]).includes(laneRef.current) && now >= invincibleUntil.current && now >= boostUntil.current) { healthRef.current -= 1; setHealth(healthRef.current); invincibleUntil.current = now + 1200; if (healthRef.current <= 0) finish('failure'); } if (phaseAge >= SKY_LIGHTNING_STRIKE_MS) { object.phase = 'done'; object.phaseStartedAt = now; } } else if (object.phase === 'done' && phaseAge >= SKY_LIGHTNING_IMPACT_MS) removed.add(object.id); } continue; }
        object.x -= (object.kind === 'bird' ? preset.birdSpeed : object.kind === 'stormRock' ? preset.speed * 1.08 : preset.speed) * delta; if (object.x < SKY_ISLAND_CONFIG.despawnX) { removed.add(object.id); continue; } const dx = Math.abs(object.x - SKY_ISLAND_CONFIG.playerX), laneY = getSkyLaneY(object.lane, laneCount), collisionY = (object.kind === 'stormRock' ? getSkyStormRockTrackingY(laneY, playerYRef.current, object.x, 130, SKY_ISLAND_CONFIG.playerX, SKY_STORM_ROCK_TRACKING_STRENGTH[difficulty]) : laneY) + (object.kind === 'stormRock' ? getSkyStormRockMotion(now - (object.motionStartedAt ?? now), object.id, object.waveAmplitude ?? 8).yOffset : 0), dy = Math.abs(collisionY - playerYRef.current); if (OBSTACLES.has(object.kind) && dx <= 12 && dy <= getSkyCollisionYThreshold(difficulty, laneCount) && now >= invincibleUntil.current) { removed.add(object.id); const collision = resolveSkyObstacleCollision(now < boostUntil.current); if (collision.consumeBoost) boostUntil.current = 0; else if (!collision.blocked) { healthRef.current -= collision.damage; setHealth(healthRef.current); invincibleUntil.current = now + SKY_ISLAND_CONFIG.playerInvincibleMs; if (healthRef.current <= 0) finish('failure'); } } else if (!OBSTACLES.has(object.kind) && dx <= SKY_ISLAND_CONFIG.collectHitboxX && dy <= SKY_ISLAND_CONFIG.collectHitboxY) { removed.add(object.id); if (object.kind === 'coin') { coinsRef.current += 1; setCoins(coinsRef.current); } else if (object.kind === 'fragment' && fragmentsRef.current < MAX_RARE_FRAGMENTS_PER_RUN) { fragmentsRef.current += 1; setFragments(fragmentsRef.current); } else if (object.kind === 'fossil') { fossilsRef.current = [...new Set([...fossilsRef.current, stageNumber])]; setFossils(fossilsRef.current); } else if (object.kind === 'health_restore') { healthRef.current = applyHealthRestore(healthRef.current, 3); setHealth(healthRef.current); } }
      } if (shouldSpawnHealthRestore(healthRef.current, 3, healthSpawned.current)) { healthSpawned.current = true; objectsRef.current.push({ id: nextId.current++, lane: Math.floor(Math.random() * laneCount), x: 108, kind: 'health_restore' }); } if (removed.size) { objectsRef.current = objectsRef.current.filter(object => !removed.has(object.id)); setObjects([...objectsRef.current]); } setBoostActive(now < boostUntil.current); setBoostCooldownMs(Math.max(0, boostReadyAt.current - now)); setInvincible(now < invincibleUntil.current); sync(); frame = requestAnimationFrame(tick); };
    frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame); }, [difficulty, duration, finish, laneCount, stageNumber, sync]);
  const objectImage = (object: SkyObject) => object.kind === 'rock' || object.kind === 'stormRock' ? skyIslandAssets.obstacles.flyingRock : object.kind === 'cloud' ? skyIslandAssets.obstacles.lightningCloud : object.kind === 'thorn' ? skyIslandAssets.obstacles.spikeCloud : object.kind === 'coin' ? skyIslandAssets.collectibles.coin : object.kind === 'health_restore' ? adventureCommonAssets.healthRestore : skyIslandAssets.collectibles.rareFragment;
  return <section className={`sky-island-game sky-runner sky-runner--stage-${stageNumber} ${paused ? 'sky-runner--paused' : ''}`} style={{ '--sky-progress': progress } as CSSProperties}><header className="sky-runner-hud"><button type="button" onClick={onExit} className="sky-exit"><ChevronLeft /> 지도</button><div className="sky-runner-hud__panel-wrap"><img className="sky-runner-hud__panel" src={skyIslandAssets.ui.hud.top} alt="" /><div className="sky-hud-slot sky-hud-slot--health">{'♥'.repeat(health)}</div><div className="sky-hud-slot sky-hud-slot--coin">{coins}</div><div className="sky-hud-slot sky-hud-slot--fragment">{fragments}</div><div className="sky-hud-slot sky-hud-slot--progress"><b>{timeLeft}초</b><small>{Math.round(progress * 100)}%</small></div></div><button type="button" className="sky-settings-button" onClick={() => { pausedRef.current = true; setPaused(true); }}><img src={skyIslandAssets.ui.buttons.pause} alt="일시정지" /></button></header>
    <div className="sky-runner-playfield" ref={playfieldRef}><img className="sky-runner-stage-bg" src={background} alt="" /><img className="sky-runner-cloud-lanes" src={skyIslandAssets.environment.cloudLane} alt="" /><div className="sky-fossil-counter">화석 {fossils.length}/3</div>{objects.map(object => <div key={object.id} ref={el => { if (el) elementRefs.current.set(object.id, el); else elementRefs.current.delete(object.id); }} className={`sky-runner-object sky-runner-object--${object.kind} ${object.phase ? `is-${object.phase}` : ''}`}>{object.kind === 'bird' ? <span className="sky-bird-cycle">{skyIslandAssets.obstacles.bird.map(src => <img key={src} src={src} alt="새떼" />)}</span> : object.kind === 'lightning' ? <>{object.phase !== 'done' && <img src={object.phase === 'striking' ? skyIslandAssets.obstacles.lightningStrike : skyIslandAssets.obstacles.lightningCloud} alt={object.phase === 'striking' ? '낙뢰' : '번개구름'} />}<i /></> : <img src={objectImage(object)} alt={object.kind === 'fossil' ? '화석조각' : ''} />}</div>)}<div ref={playerRef} className={`sky-runner-player-anchor ${boostActive ? 'sky-runner-player-anchor--boosted' : ''}`} data-lane={laneIndex}><SkyIslandPlayer invincible={invincible} bank={bank} outcome={outcome} started={!tutorial} /></div></div>
    <footer className="sky-runner-controls"><div className="sky-runner-control-cluster"><button type="button" aria-label="방어막 사용" className={`sky-boost-button ${boostActive ? 'is-active' : boostCooldownMs ? 'is-cooldown' : 'is-ready'}`} onPointerDown={activateBoost}><img src={skyIslandAssets.ui.buttons.shield} alt="" /><span>{boostCooldownMs ? Math.ceil(boostCooldownMs/1000) : '방어막'}</span></button><div className="sky-runner-paddle">{([[1,skyIslandAssets.ui.buttons.moveUp,'위'],[-1,skyIslandAssets.ui.buttons.moveDown,'아래']] as const).map(([direction,image,label]) => <button key={direction} type="button" onPointerDown={() => moveLane(direction)}><img src={image} alt={label} /></button>)}</div></div></footer>
    {outcome === 'treasure' && !externalMainModalOpen && <div className="sky-treasure-event" role="dialog" aria-modal="true" aria-label="하늘섬 최종 보물상자"><h2>Stage 3 클리어!</h2><p>{treasurePhase === 'closed' ? '보물상자에는 무엇이 들어 있을까요?' : treasurePhase === 'opening' ? '상자를 여는 중이에요…' : committedRewards?.relicOutcome?.acquired ? '하늘섬 유물 부품을 찾았어요!' : '이번에는 유물 부품을 발견하지 못했어요.'}</p><AdventureFinalTreasure phase={treasurePhase} closedImage={lavaValleyStage3Assets.treasureChestClosed} openImage={lavaValleyStage3Assets.treasureChestOpen} effectImage={lavaValleyStage3Assets.treasureOpenEffect} onOpen={openFinalTreasure} className="sky-final-treasure-button" />{treasurePhase === 'open' && committedRewards?.relicOutcome && <div className={`lava-relic-result ${committedRewards.relicOutcome.acquired ? 'is-acquired' : ''}`}>{committedRewards.relicOutcome.partImage ? <img src={committedRewards.relicOutcome.partImage} alt={committedRewards.relicOutcome.partName ?? '하늘섬 유물 부품'} /> : <Gem aria-label="하늘섬 유물 부품" />}<span><strong>이번 획득: {committedRewards.relicOutcome.acquired ? committedRewards.relicOutcome.partName : '없음'}</strong><b>현재 유물: {committedRewards.relicOutcome.ownedPartCount}/{committedRewards.relicOutcome.goal}</b></span></div>}</div>}
    {!assetsReady && <div className="sky-runner-overlay">하늘 모험 준비 중...</div>}{assetsReady && tutorial && <AdventureStageIntro config={intro} onStart={beginRun} />}
    {paused && !externalMainModalOpen && <div className="sky-settings-backdrop"><section className="sky-settings-panel"><div className="sky-settings-heading"><h2>잠깐 쉬어요</h2><button onClick={() => { pausedRef.current = false; setPaused(false); }}><X /></button></div><fieldset><legend>난이도</legend>{([['normal','기본'],['hard','어려움']] as const).map(([value,label]) => { const unlocked = isAdventureDifficultyUnlocked('skyIsland', stageNumber, value, relicPartCount); return <button key={value} disabled={!unlocked} aria-pressed={difficulty === value} onClick={() => chooseDifficulty(value)}>{label}{!unlocked ? ' (유물 부품 필요)' : ''}</button>; })}</fieldset><button className="sky-settings-resume" onClick={() => { pausedRef.current = false; setPaused(false); }}>계속하기</button><button className="sky-settings-resume" onClick={() => onRetry(true)}>처음부터</button></section></div>}
    {(outcome === 'success' || outcome === 'failure') && !externalMainModalOpen && <div className="sky-modal"><section><h2>{outcome === 'success' ? `Stage ${stageNumber} 완료!` : '다시 날아볼까요?'}</h2>{outcome === 'success' && <div className="sky-runner-result"><span>지갑 코인 +{committedRewards?.coins ?? 0}</span><span>희귀조각 +{committedRewards?.rareFragments ?? 0}</span><span>화석 {fossils.length}/3</span>{committedRewards?.relicOutcome && <><span>이번 획득: {committedRewards.relicOutcome.acquired ? committedRewards.relicOutcome.partName : '없음'}</span><span>현재 유물: {committedRewards.relicOutcome.ownedPartCount}/{committedRewards.relicOutcome.goal}</span></>}</div>}<div><button onClick={() => outcome === 'success' ? onRetry() : onRetry(true)}><RotateCcw /> 다시 도전</button><button onClick={onExit}>지도</button></div></section></div>}
  </section>;
}
