import type { SokobanPuzzleConfig } from './types';

export const RUINS_SOKOBAN_STAGE_2: readonly SokobanPuzzleConfig[] = [
  {
    id: "ruins-sokoban-2-1", stage: 2, mission: 1, title: "기둥을 돌아 자리 잡기",
    instruction: '상자를 모두 제단에 놓으세요.',
    board: ["########","# . .$ #","#      #","#  ##$ #","#     @#","#     E#","########"],
    completion: 'boxesOnGoals', highlights: [], showDeadlockHint: false,
    expectedMinPushes: 6, expectedMinMoves: 18,
    tutorial: { introText: '상자의 길과 밀 순서를 살펴보세요.', hintSteps: ["밀 자리를 찾아봐요.","위 상자 오른쪽을 봐요.","위 상자를 왼쪽으로 한 칸 밀어봐요."] },
  },
  {
    id: "ruins-sokoban-2-2", stage: 2, mission: 2, title: "먼저 비워야 할 길",
    instruction: '상자를 모두 제단에 놓으세요.',
    board: ["########","# $. . #","#   #  #","# #  # #","# @  $ #","#    #E#","########"],
    completion: 'boxesOnGoals', highlights: [], showDeadlockHint: false,
    expectedMinPushes: 8, expectedMinMoves: 31,
    tutorial: { introText: '상자의 길과 밀 순서를 살펴보세요.', hintSteps: ["순서를 생각해요.","아래 오른쪽 상자를 봐요.","그 상자를 왼쪽으로 한 칸 밀어봐요."] },
  },
  {
    id: "ruins-sokoban-2-3", stage: 2, mission: 3, title: "좁은 통로의 차례",
    instruction: '상자를 모두 제단에 놓으세요.',
    board: ["########","# . .  #","#  # . #","# $$ $ #","#   #  #","# @   E#","########"],
    completion: 'boxesOnGoals', highlights: [], showDeadlockHint: false,
    expectedMinPushes: 8, expectedMinMoves: 23,
    tutorial: { introText: '상자의 길과 밀 순서를 살펴보세요.', hintSteps: ["통로를 막지 마세요.","왼쪽 상자를 봐요.","왼쪽 상자를 위로 한 칸 밀어봐요."] },
  },
  {
    id: "ruins-sokoban-2-4", stage: 2, mission: 4, title: "멀어졌다 가까워져요",
    instruction: '상자를 모두 제단에 놓으세요.',
    board: ["#######","#     #","#  . .#","# @$  #","#  # $#","#    E#","#######"],
    completion: 'boxesOnGoals', highlights: [], showDeadlockHint: false,
    expectedMinPushes: 5, expectedMinMoves: 17,
    tutorial: { introText: '상자의 길과 밀 순서를 살펴보세요.', hintSteps: ["멀어지는 길도 생각해요.","왼쪽 상자 오른쪽을 봐요.","그 상자를 오른쪽으로 한 칸 밀어봐요."] },
  },
  {
    id: "ruins-sokoban-2-5", stage: 2, mission: 5, title: "비워야 지나가요",
    instruction: '상자를 모두 제단에 놓으세요.',
    board: ["########","# .  * #","# #$#  #","#      #","#  . $ #","# @   E#","########"],
    completion: 'boxesOnGoals', highlights: [], showDeadlockHint: false,
    expectedMinPushes: 8, expectedMinMoves: 16,
    tutorial: { introText: '상자의 길과 밀 순서를 살펴보세요.', hintSteps: ["놓인 상자도 길을 막아요.","오른쪽 아래 상자를 봐요.","그 상자를 위로 한 칸 밀어봐요."] },
  },
  {
    id: "ruins-sokoban-2-6", stage: 2, mission: 6, title: "서로 막는 두 상자",
    instruction: '상자를 모두 제단에 놓으세요.',
    board: ["########","# ..   #","#  #   #","# $$   #","#  #   #","#  @  E#","########"],
    completion: 'boxesOnGoals', highlights: [], showDeadlockHint: false,
    expectedMinPushes: 6, expectedMinMoves: 17,
    tutorial: { introText: '상자의 길과 밀 순서를 살펴보세요.', hintSteps: ["다른 상자의 길도 남겨요.","왼쪽 상자를 먼저 봐요.","왼쪽 상자를 위로 한 칸 밀어봐요."] },
  },
  {
    id: "ruins-sokoban-2-7", stage: 2, mission: 7, title: "어느 상자가 어느 제단으로?",
    instruction: '상자를 모두 제단에 놓으세요.',
    board: ["########","#.# . .#","# # #  #","#$# $$ #","#@     #","#     E#","########"],
    completion: 'boxesOnGoals', highlights: [], showDeadlockHint: false,
    expectedMinPushes: 9, expectedMinMoves: 25,
    tutorial: { introText: '상자의 길과 밀 순서를 살펴보세요.', hintSteps: ["갈 수 있는 제단을 살펴봐요.","왼쪽 좁은 방을 봐요.","왼쪽 상자를 위로 한 칸 밀어봐요."] },
  },
  {
    id: "ruins-sokoban-2-8", stage: 2, mission: 8, title: "제단에서 잠깐 내려요",
    instruction: '상자를 모두 제단에 놓으세요.',
    board: ["########","# .  * #","#  #$  #","#      #","# #  *@#","#     E#","########"],
    completion: 'boxesOnGoals', highlights: [], showDeadlockHint: false,
    expectedMinPushes: 9, expectedMinMoves: 19,
    tutorial: { introText: '상자의 길과 밀 순서를 살펴보세요.', hintSteps: ["제단 위 상자를 다시 써요.","오른쪽 아래 제단을 봐요.","그 상자를 위로 한 칸 밀어봐요."] },
  },
  {
    id: "ruins-sokoban-2-9", stage: 2, mission: 9, title: "막힌 길을 다시 열어요",
    instruction: '상자를 모두 제단에 놓으세요.',
    board: ["#########","# .   * #","# ## $@ #","#   #   #","#  .  $ #","#      E#","#########"],
    completion: 'boxesOnGoals', highlights: [], showDeadlockHint: false,
    expectedMinPushes: 9, expectedMinMoves: 18,
    tutorial: { introText: '상자의 길과 밀 순서를 살펴보세요.', hintSteps: ["먼저 길을 열어요.","오른쪽 위 제단을 봐요.","그 상자를 왼쪽으로 한 칸 밀어봐요."] },
  },
  {
    id: "ruins-sokoban-2-10", stage: 2, mission: 10, title: "유적 훈련 최종 시험",
    instruction: '상자를 모두 제단에 놓으세요.',
    board: ["#########","# . * . #","#   # $ #","# $  @  #","# #  .$ #","#      E#","#########"],
    completion: 'boxesOnGoals', highlights: [], showDeadlockHint: false,
    expectedMinPushes: 10, expectedMinMoves: 30,
    tutorial: { introText: '상자의 길과 밀 순서를 살펴보세요.', hintSteps: ["상자들의 길을 함께 봐요.","위쪽 가운데 상자를 봐요.","그 상자를 왼쪽으로 한 칸 밀어봐요."] },
  },
] as const;
