import type { RuinsMirrorFixedPuzzleConfig } from './types';

export const RUINS_MIRROR_STAGE_2_MISSIONS: readonly RuinsMirrorFixedPuzzleConfig[] = [
  {
    id: 'ruins-mirror-2-1', mode: 'fixed', mission: 1,
    title: '넓어진 유적', instruction: '거울을 터치해 큰 보드 끝의 제단까지 빛을 보내세요.',
    grid: { columns: 7, rows: 7 }, emitter: { column: 0, row: 6, direction: 'east' }, target: { column: 6, row: 0 },
    blockers: [{ column: 4, row: 6 }, { column: 0, row: 3 }, { column: 5, row: 4 }],
    mirrors: [
      { id: 'm1', column: 2, row: 6, initial: 'backslash', rotatable: true },
      { id: 'm2', column: 2, row: 2, initial: 'backslash', rotatable: true },
      { id: 'm3', column: 6, row: 2, initial: 'backslash', rotatable: true },
    ],
    solution: { m1: 'slash', m2: 'slash', m3: 'slash' }, expectedMinimumReflections: 3,
  },
  {
    id: 'ruins-mirror-2-2', mode: 'fixed', mission: 2,
    title: '움직이지 않는 거울', instruction: '테두리가 잠긴 고정 거울의 방향을 거꾸로 따라가 보세요.',
    grid: { columns: 7, rows: 7 }, emitter: { column: 0, row: 6, direction: 'east' }, target: { column: 1, row: 1 },
    blockers: [{ column: 5, row: 6 }, { column: 2, row: 3 }, { column: 5, row: 0 }],
    mirrors: [
      { id: 'm1', column: 3, row: 6, initial: 'backslash', rotatable: true },
      { id: 'f1', column: 3, row: 3, initial: 'slash', rotatable: false },
      { id: 'm2', column: 6, row: 3, initial: 'backslash', rotatable: true },
      { id: 'm3', column: 6, row: 1, initial: 'slash', rotatable: true },
    ],
    solution: { m1: 'slash', m2: 'slash', m3: 'backslash' }, expectedMinimumReflections: 4,
  },
  {
    id: 'ruins-mirror-2-3', mode: 'fixed', mission: 3,
    title: '막힌 지름길', instruction: '가까운 길에 속지 말고 필요한 거울만 찾아 회전하세요.',
    grid: { columns: 7, rows: 7 }, emitter: { column: 0, row: 6, direction: 'east' }, target: { column: 0, row: 2 },
    blockers: [{ column: 3, row: 5 }, { column: 0, row: 4 }, { column: 3, row: 2 }, { column: 5, row: 4 }],
    mirrors: [
      { id: 'm1', column: 1, row: 6, initial: 'backslash', rotatable: true },
      { id: 'f1', column: 1, row: 4, initial: 'slash', rotatable: false },
      { id: 'm2', column: 4, row: 4, initial: 'slash', rotatable: true },
      { id: 'm3', column: 4, row: 6, initial: 'backslash', rotatable: true },
      { id: 'm4', column: 2, row: 6, initial: 'slash', rotatable: true },
      { id: 'f2', column: 2, row: 2, initial: 'backslash', rotatable: false },
      { id: 'dummy', column: 6, row: 0, initial: 'slash', rotatable: true },
    ],
    solution: { m1: 'slash', m2: 'backslash', m3: 'slash', m4: 'backslash', dummy: 'slash' }, expectedMinimumReflections: 6,
  },
  {
    id: 'ruins-mirror-2-4', mode: 'fixed', mission: 4,
    title: '두 갈래의 빛', instruction: '분기석에서 나뉜 빛으로 두 제단을 함께 밝히세요.',
    grid: { columns: 7, rows: 7 }, emitter: { column: 3, row: 6, direction: 'north' }, target: { column: 1, row: 6 },
    targets: [{ column: 1, row: 6 }, { column: 5, row: 0 }], splitters: [{ id: 's1', column: 3, row: 3, outputs: ['west', 'east'] }],
    blockers: [{ column: 0, row: 3 }, { column: 6, row: 3 }],
    mirrors: [
      { id: 'm1', column: 1, row: 3, initial: 'backslash', rotatable: true },
      { id: 'm2', column: 5, row: 3, initial: 'backslash', rotatable: true },
    ],
    solution: { m1: 'slash', m2: 'slash' }, expectedMinimumReflections: 2,
  },
  {
    id: 'ruins-mirror-2-5', mode: 'fixed', mission: 5,
    title: '한쪽은 먼 길', instruction: '오른쪽 빛은 고정 거울을 이용해 장애물을 돌아가야 해요.',
    grid: { columns: 7, rows: 7 }, emitter: { column: 3, row: 6, direction: 'north' }, target: { column: 1, row: 1 },
    targets: [{ column: 1, row: 1 }, { column: 6, row: 5 }], splitters: [{ id: 's1', column: 3, row: 4, outputs: ['west', 'east'] }],
    blockers: [{ column: 5, row: 4 }, { column: 5, row: 3 }, { column: 3, row: 1 }, { column: 0, row: 4 }],
    mirrors: [
      { id: 'm1', column: 1, row: 4, initial: 'slash', rotatable: true },
      { id: 'm2', column: 4, row: 4, initial: 'backslash', rotatable: true },
      { id: 'f1', column: 4, row: 2, initial: 'backslash', rotatable: false },
      { id: 'm3', column: 2, row: 2, initial: 'backslash', rotatable: true },
      { id: 'm4', column: 2, row: 5, initial: 'slash', rotatable: true },
    ],
    solution: { m1: 'backslash', m2: 'slash', m3: 'slash', m4: 'backslash' }, expectedMinimumReflections: 5,
  },
  {
    id: 'ruins-mirror-2-6', mode: 'fixed', mission: 6,
    title: '태양 신전의 시험', instruction: '분기 전 경로와 두 갈래를 모두 읽어 두 제단을 밝히세요.',
    grid: { columns: 7, rows: 7 }, emitter: { column: 0, row: 6, direction: 'east' }, target: { column: 6, row: 0 },
    targets: [{ column: 6, row: 0 }, { column: 6, row: 6 }], splitters: [{ id: 's1', column: 4, row: 4, outputs: ['north', 'south'] }],
    blockers: [{ column: 3, row: 6 }, { column: 0, row: 4 }, { column: 5, row: 4 }, { column: 4, row: 0 }, { column: 5, row: 5 }],
    mirrors: [
      { id: 'm1', column: 1, row: 6, initial: 'backslash', rotatable: true },
      { id: 'm2', column: 1, row: 4, initial: 'backslash', rotatable: true },
      { id: 'f1', column: 4, row: 2, initial: 'slash', rotatable: false },
      { id: 'm3', column: 6, row: 2, initial: 'backslash', rotatable: true },
      { id: 'm4', column: 4, row: 6, initial: 'backslash', rotatable: true },
      { id: 'dummy', column: 2, row: 0, initial: 'slash', rotatable: true },
    ],
    solution: { m1: 'slash', m2: 'slash', m3: 'slash', m4: 'backslash', dummy: 'slash' }, expectedMinimumReflections: 5,
  },
] as const;
