import type { IceMissionConfig, IceMissionId } from './iceMissionTypes';

const base = {
  stage: 1 as const, kind: 'tutorial' as const, dinosaur: 'training-fossil', fossilPartIds: ['training-bone'], playerSpeed: 195,
  production: { speed: 26, processItemCount: 1, processTimes: { feeder: .35, cutter: .6, cracker: .6, washer: .55 }, sharedMachineIds: [], backlogCapacity: 3, queuePolicy: 'fifo' as const, restartSurgeMultiplier: 1.45, restartSurgeDuration: 4, arcadeLoop: false, spawnInterval: 6, targetCompleted: 1, overloadPauseDuration: 0 },
  issues: { allowedTypes: ['freeze', 'jam'] as const, interval: [12, 24] as const, warningDuration: 1.2, repairDuration: .55, wrongToolPenalty: .45, maxSimultaneous: 1 as const, severity: 'low' as const },
  penguins: { count: 0 as const, interferenceRate: 0, behaviorPatterns: [] as const },
  objective: { requiredParts: ['training-bone'], completionType: 'partMounted' as const }, reward: { type: 'none' as const },
};

export type PlayableIceMissionId = '1-1' | '1-2' | '1-3' | '2-1' | '2-2' | '2-3' | '2-4';
const stage2Tutorial = (title: string, sample: string) => ({ startTitle: title, startBody: `${sample}을 복원하세요!\n기계가 멈추면 직접 찾아가 고쳐주세요.`, startButton: '시작', completionMessage: `${sample} 복원 완료!`, requireStartAction: false, guidedIssueTypes: [] as const });
const stage2Base = { ...base, stage: 2 as const, kind: 'sample' as const, playerSpeed: 220, issues: { ...base.issues, warningDuration: 1.6, repairDuration: .9, wrongToolPenalty: .35 }, penguins: { count: 1 as const, interferenceRate: .6, behaviorPatterns: ['blockConveyor', 'switchOff'] as const } };

export const ICE_MISSION_CONFIGS: Readonly<Record<PlayableIceMissionId, IceMissionConfig>> = {
  '1-1': { ...base, id: '1-1', nextMissionId: '1-2', title: '생산라인 배우기', tutorial: { startTitle: '화석을 복원해보자!', startBody: '얼음 속 화석이 기계를 지나가면\n조금씩 모습을 드러내요.\n끝까지 잘 가는지 지켜봐요!', startButton: '시작!', completionMessage: '화석이 복원되는 과정을 배웠어요!', requireStartAction: true, guidedIssueTypes: [] }, mapTemplate: 'LAYOUT_A_BASIC_TWO_FLOOR', durationSec: 65, targetPlayTime: [45, 60], eventPatternId: 'stage1_observe' },
  '1-2': { ...base, id: '1-2', nextMissionId: '1-3', title: '수리 배우기', tutorial: { startTitle: '기계가 멈췄어요!', startBody: '기계에 문제가 생기면 화석도 멈춰요.\n맞는 도구를 골라 고쳐주세요!', startButton: '고치러 가기!', completionMessage: '기계를 고치는 방법을 배웠어요!', requireStartAction: false, guidedIssueTypes: ['freeze'] }, mapTemplate: 'LAYOUT_A_BASIC_TWO_FLOOR', durationSec: 85, targetPlayTime: [60, 75], production: { ...base.production, speed: 25, processItemCount: 3, backlogCapacity: 2 }, eventPatternId: 'stage1_repair' },
  '1-3': { ...base, id: '1-3', nextMissionId: null, title: '운영 배우기', tutorial: { startTitle: '이제 공장을 운영해보자!', startBody: '이번에는 여러 문제가 생겨요.\n멈춘 곳을 찾아서 하나씩 해결해봐요!', startButton: '출발!', completionMessage: '이제 복원 기지를 운영할 수 있어요!', requireStartAction: false, guidedIssueTypes: ['penguin_interference'] }, mapTemplate: 'LAYOUT_B_CENTER_LADDER', durationSec: 110, targetPlayTime: [75, 100], production: { ...base.production, speed: 24, processItemCount: 3, backlogCapacity: 3, restartSurgeMultiplier: 1.55, restartSurgeDuration: 5 }, issues: { ...base.issues, allowedTypes: ['freeze', 'jam', 'penguin_interference'] }, penguins: { count: 1, interferenceRate: 1, behaviorPatterns: ['blockConveyor'] }, eventPatternId: 'stage1_operate' },
  '2-1': { ...stage2Base, id: '2-1', nextMissionId: '2-2', title: '티라노 발톱 화석', dinosaur: 'tyrannosaurus', fossilPartIds: ['trex-claw'], tutorial: { ...stage2Tutorial('티라노 발톱 화석', '티라노사우루스 발톱 화석'), startBody: '빠른 생산 라인을 운영해 표본 8개를 완성하세요.\n문제는 한 번의 수리 동작으로 복구하고, 펭귄은 기계에 닿기 전에 막아야 해요.' }, mapTemplate: 'LAYOUT_B_CENTER_LADDER', durationSec: 105, targetPlayTime: [75, 95], production: { ...base.production, speed: 34, processItemCount: 5, processTimes: { feeder: .2, cutter: .32, cracker: .32, washer: .3 }, backlogCapacity: 4, restartSurgeMultiplier: 1.85, restartSurgeDuration: 6, arcadeLoop: true, spawnInterval: 2.2, targetCompleted: 8, overloadPauseDuration: 2.2 }, issues: { ...stage2Base.issues, allowedTypes: ['freeze', 'jam', 'penguin_interference'], warningDuration: .8, repairDuration: .72, maxSimultaneous: 1 }, objective: { requiredParts: ['trex-claw'], completionType: 'sampleDisplay' }, reward: { type: 'sampleCollection', id: 'sample_trex_claw' }, eventPatternId: 'stage2_basic' },
  '2-2': { ...stage2Base, id: '2-2', nextMissionId: '2-3', title: '트리케라 작은 뿔', dinosaur: 'triceratops', fossilPartIds: ['tricera-small-horn'], tutorial: stage2Tutorial('트리케라 작은 뿔', '트리케라톱스 작은 뿔 화석'), mapTemplate: 'LAYOUT_C_U_LINE', durationSec: 175, targetPlayTime: [135, 155], production: { ...base.production, speed: 13, processItemCount: 3, backlogCapacity: 4, restartSurgeMultiplier: 1.4 }, issues: { ...stage2Base.issues, allowedTypes: ['freeze', 'jam', 'power'], maxSimultaneous: 2 }, objective: { requiredParts: ['tricera-small-horn'], completionType: 'sampleDisplay' }, reward: { type: 'sampleCollection', id: 'sample_triceratops_horn' }, eventPatternId: 'stage2_priority' },
  '2-3': { ...stage2Base, id: '2-3', nextMissionId: '2-4', title: '스피노 신경가시', dinosaur: 'spinosaurus', fossilPartIds: ['spino-neural-spine'], tutorial: stage2Tutorial('스피노 신경가시', '스피노사우루스 신경가시 화석'), mapTemplate: 'LAYOUT_D_MERGE', durationSec: 205, targetPlayTime: [160, 185], production: { ...base.production, speed: 11, processItemCount: 4, sharedMachineIds: ['cracker'], backlogCapacity: 5, queuePolicy: 'alternate', restartSurgeMultiplier: 1.55, restartSurgeDuration: 7 }, issues: { ...stage2Base.issues, allowedTypes: ['freeze', 'jam', 'power', 'penguin_interference'], maxSimultaneous: 2 }, penguins: { ...stage2Base.penguins, count: 2 }, objective: { requiredParts: ['spino-neural-spine'], completionType: 'sampleDisplay' }, reward: { type: 'sampleCollection', id: 'sample_spinosaurus_spine' }, eventPatternId: 'stage2_backlog' },
  '2-4': { ...stage2Base, id: '2-4', nextMissionId: null, title: '소형 공룡 발 화석 세트', dinosaur: 'small-dinosaur', fossilPartIds: ['ankle', 'toes', 'claw'], tutorial: stage2Tutorial('마지막 표본 복원!', '소형 공룡 발 화석 세트'), mapTemplate: 'LAYOUT_E_PARTIAL_THREE_FLOOR', durationSec: 245, targetPlayTime: [190, 225], production: { ...base.production, speed: 9.5, processItemCount: 5, sharedMachineIds: ['cracker'], backlogCapacity: 5, queuePolicy: 'missionSequence', restartSurgeMultiplier: 1.6, restartSurgeDuration: 8 }, issues: { ...stage2Base.issues, allowedTypes: ['freeze', 'jam', 'power', 'conveyor_block', 'penguin_interference'], maxSimultaneous: 2, repairDuration: 1.05 }, penguins: { ...stage2Base.penguins, count: 2, interferenceRate: .8, behaviorPatterns: ['blockConveyor', 'dropIceDebris'] }, objective: { requiredParts: ['ankle', 'toes', 'claw'], completionType: 'sampleDisplay' }, reward: { type: 'sampleCollection', id: 'sample_dinosaur_foot' }, eventPatternId: 'stage2_final' },
};

export function isPlayableIceMissionId(value: string | null): value is keyof typeof ICE_MISSION_CONFIGS { return Boolean(value && value in ICE_MISSION_CONFIGS); }
export function getIceMissionConfig(id: IceMissionId): IceMissionConfig | undefined { return ICE_MISSION_CONFIGS[id as keyof typeof ICE_MISSION_CONFIGS]; }
